name: xsoulspace_ysdk_games_js
description: Generated dart:js_interop bindings and Dart wrappers for Yandex Games SDK.
version: 0.1.0-beta.1
repository: https://github.com/xsoulspace/xsoulspace_packages
homepage: https://github.com/xsoulspace/xsoulspace_packages/tree/main/pkgs/xsoulspace_ysdk_games_js
issue_tracker: https://github.com/xsoulspace/xsoulspace_packages/issues

topics:
  - yandex
  - games
  - js-interop
  - web
  - xsoulspace

platforms:
  web:

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  meta: ^1.19.0
  xsoulspace_js_interop_runtime: ^0.1.0-dev.1

dev_dependencies:
  archive: ^4.0.9
  crypto: ^3.0.7
  http: ^1.6.0
  lints: ^6.1.0
  path: ^1.9.1
  test: ^1.31.2
  xsoulspace_js_interop_codegen: ^0.1.0-dev.1
  xsoulspace_lints: ^0.1.2
