name: xsoulspace_ysdk_games_js
description: Generated dart:js_interop bindings and Dart wrappers for Yandex Games SDK.
version: 0.1.0
repository: https://github.com/xsoulspace/xsoulspace_packages
homepage: https://github.com/xsoulspace/xsoulspace_packages/tree/main/pkgs/xsoulspace_ysdk_games_js
issue_tracker: https://github.com/xsoulspace/xsoulspace_packages/issues

topics:
  - yandex
  - games
  - js-interop
  - web
  - xsoulspace

platforms:
  web:

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  meta: ^1.16.0

dev_dependencies:
  archive: ^4.0.2
  crypto: ^3.0.6
  http: ^1.5.0
  lints: ^6.0.0
  path: ^1.9.1
  test: ^1.26.3
  xsoulspace_js_interop_codegen:
    path: ../xsoulspace_js_interop_codegen
  xsoulspace_lints: ^0.1.2
