name: xsoulspace_monetization_google_apple
description: A Flutter package for integrating Google Play and Apple App Store
  in-app purchases.
version: 0.8.0

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  app_settings: ^6.1.1
  collection: ^1.19.1
  flutter:
    sdk: flutter
  from_json_to_json: ^0.3.0
  in_app_purchase: ^3.2.3
  in_app_purchase_storekit: ^0.4.4
  xsoulspace_monetization_interface: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.2

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: GoogleApplePurchaseProviderPlugin
