name: xsoulspace_monetization_google_apple
description: A new Flutter package.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  from_json_to_json: ^0.2.1
  in_app_purchase: ^3.2.0
  xsoulspace_monetization_interface:
    path: ../xsoulspace_monetization_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.0
