name: xsoulspace_monetization_google_apple
description: A Flutter package for integrating Google Play and Apple App Store
  in-app purchases.
version: 0.8.1
repository: https://github.com/xsoulspace/dart_flutter_packages
homepage: https://github.com/xsoulspace/dart_flutter_packages/tree/main/pkgs/xsoulspace_monetization_google_apple
issue_tracker: https://github.com/xsoulspace/dart_flutter_packages/issues

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  app_settings: ^7.0.0
  collection: ^1.19.1
  flutter:
    sdk: flutter
  from_json_to_json: ^0.4.0
  in_app_purchase: ^3.2.3
  in_app_purchase_storekit: ^0.4.8
  xsoulspace_monetization_interface: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.1.0
  xsoulspace_lints: ^0.1.2

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: GoogleApplePurchaseProviderPlugin
