name: universal_storage_filesystem
description: Filesystem storage provider for universal_storage_interface.
version: 0.1.0-dev.4
homepage: https://github.com/xsoulspace/universal_storage_sync
repository: https://github.com/xsoulspace/universal_storage_sync
issue_tracker: https://github.com/xsoulspace/universal_storage_sync/issues
documentation: https://github.com/xsoulspace/universal_storage_sync/tree/main/pkgs/universal_storage_filesystem

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  path: ^1.9.1
  universal_storage_interface: ^0.1.0-dev.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  xsoulspace_lints: ^0.1.0
