name: universal_storage_filesystem
description: Filesystem storage provider for universal_storage_interface.
version: 0.1.0-dev.3
publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  path: ^1.9.1
  universal_storage_interface: ^0.1.0-dev.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  xsoulspace_lints: ^0.1.0
