name: hex_guides_web
description: Interactive Hexagonal Grid Guides.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # No specific dependencies for the hex logic itself yet
  # For web, 'html' is implicitly available.
  # We might add a simple state management or UI helper later if needed.

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^3.0.0
  test: ^1.24.0
