name: universal_storage_sync_utils_flutter
description: Flutter implementations for universal_storage_sync_utils path picking and macOS bookmark access.
version: 0.1.0-dev.1
homepage: https://github.com/xsoulspace/universal_storage_sync/tree/main/pkgs/universal_storage_sync_utils_flutter
repository: https://github.com/xsoulspace/universal_storage_sync
issue_tracker: https://github.com/xsoulspace/universal_storage_sync/issues
documentation: https://github.com/xsoulspace/universal_storage_sync/tree/main/pkgs/universal_storage_sync_utils_flutter

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  macos_secure_bookmarks: ^0.2.1
  path_provider: ^2.1.5
  universal_io: ^2.3.1
  universal_storage_interface: ^0.1.0-dev.12
  universal_storage_sync_utils: ^0.1.0-dev.13
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.2
