name: xsoulspace_monetization_rustore
description: A new Flutter package.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rustore_billing: ^9.1.0
  xsoulspace_monetization_interface:
    path: ../xsoulspace_monetization_interface
  xsoulspace_foundation: ^0.2.0
  universal_io: ^2.2.2
  from_json_to_json: ^0.2.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.0
