// Autogenerated from Pigeon (v26.1.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers, lines_longer_than_80_chars, prefer_final_parameters, prefer_expression_function_bodies, prefer_constructors_over_static_methods, avoid_types_on_closure_parameters, parameter_assignments, avoid_catches_without_on_clauses, cascade_invocations

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every(
          (MapEntry<Object?, Object?> entry) =>
              (b as Map<Object?, Object?>).containsKey(entry.key) &&
              _deepEquals(entry.value, b[entry.key]),
        );
  }
  return a == b;
}

enum RustoreBillingTheme { light, dark, system, unknown }

enum RustorePurchaseAvailabilityStatus { available, unavailable, unknown }

enum RustoreProductStatus { active, inactive, unknown }

enum RustoreProductType { consumable, nonConsumable, subscription, unknown }

enum RustoreSubscriptionPeriodType { trial, intro, main, grace, hold, unknown }

enum RustorePurchaseType { oneStep, twoStep, undefined, unknown }

enum RustorePurchaseStatus {
  created,
  invoiceCreated,
  paid,
  confirmed,
  cancelled,
  reversed,
  consumed,
  closed,
  active,
  paused,
  terminated,
  unknown,
}

enum RustorePreferredPurchaseType { oneStep, twoStep, unknown }

enum RustoreProductPurchaseResultType { success, cancelled, failure, unknown }

enum RustoreExceptionType {
  notInstalled,
  outdated,
  userUnauthorized,
  general,
  unknown,
}

class RustoreBillingConfig {
  RustoreBillingConfig({
    required this.consoleApplicationId,
    required this.deeplinkScheme,
    this.debugLogs = false,
    this.defaultTheme = RustoreBillingTheme.system,
    this.enableLogging = false,
  });

  String consoleApplicationId;

  String deeplinkScheme;

  bool debugLogs;

  RustoreBillingTheme defaultTheme;

  bool enableLogging;

  List<Object?> _toList() {
    return <Object?>[
      consoleApplicationId,
      deeplinkScheme,
      debugLogs,
      defaultTheme,
      enableLogging,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RustoreBillingConfig decode(Object result) {
    result as List<Object?>;
    return RustoreBillingConfig(
      consoleApplicationId: result[0]! as String,
      deeplinkScheme: result[1]! as String,
      debugLogs: result[2]! as bool,
      defaultTheme: result[3]! as RustoreBillingTheme,
      enableLogging: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RustoreBillingConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RustorePurchaseAvailabilityResult {
  RustorePurchaseAvailabilityResult({required this.status, this.cause});

  RustorePurchaseAvailabilityStatus status;

  RustoreException? cause;

  List<Object?> _toList() {
    return <Object?>[status, cause];
  }

  Object encode() {
    return _toList();
  }

  static RustorePurchaseAvailabilityResult decode(Object result) {
    result as List<Object?>;
    return RustorePurchaseAvailabilityResult(
      status: result[0]! as RustorePurchaseAvailabilityStatus,
      cause: result[1] as RustoreException?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RustorePurchaseAvailabilityResult ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RustoreProduct {
  RustoreProduct({
    required this.productId,
    required this.productType,
    required this.productStatus,
    this.title,
    this.description,
    this.price,
    this.priceLabel,
    this.currency,
    this.language,
    this.subscriptionInfo,
  });

  String productId;

  RustoreProductType productType;

  RustoreProductStatus productStatus;

  String? title;

  String? description;

  int? price;

  String? priceLabel;

  String? currency;

  String? language;

  RustoreProductSubscriptionInfo? subscriptionInfo;

  List<Object?> _toList() {
    return <Object?>[
      productId,
      productType,
      productStatus,
      title,
      description,
      price,
      priceLabel,
      currency,
      language,
      subscriptionInfo,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RustoreProduct decode(Object result) {
    result as List<Object?>;
    return RustoreProduct(
      productId: result[0]! as String,
      productType: result[1]! as RustoreProductType,
      productStatus: result[2]! as RustoreProductStatus,
      title: result[3] as String?,
      description: result[4] as String?,
      price: result[5] as int?,
      priceLabel: result[6] as String?,
      currency: result[7] as String?,
      language: result[8] as String?,
      subscriptionInfo: result[9] as RustoreProductSubscriptionInfo?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RustoreProduct || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RustoreProductSubscriptionInfo {
  RustoreProductSubscriptionInfo({required this.periods});

  List<RustoreProductSubscriptionPeriod> periods;

  List<Object?> _toList() {
    return <Object?>[periods];
  }

  Object encode() {
    return _toList();
  }

  static RustoreProductSubscriptionInfo decode(Object result) {
    result as List<Object?>;
    return RustoreProductSubscriptionInfo(
      periods: (result[0] as List<Object?>?)!
          .cast<RustoreProductSubscriptionPeriod>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RustoreProductSubscriptionInfo ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RustoreProductSubscriptionPeriod {
  RustoreProductSubscriptionPeriod({
    required this.type,
    required this.durationIso,
    this.price,
    this.priceLabel,
    this.currency,
  });

  RustoreSubscriptionPeriodType type;

  String durationIso;

  int? price;

  String? priceLabel;

  String? currency;

  List<Object?> _toList() {
    return <Object?>[type, durationIso, price, priceLabel, currency];
  }

  Object encode() {
    return _toList();
  }

  static RustoreProductSubscriptionPeriod decode(Object result) {
    result as List<Object?>;
    return RustoreProductSubscriptionPeriod(
      type: result[0]! as RustoreSubscriptionPeriodType,
      durationIso: result[1]! as String,
      price: result[2] as int?,
      priceLabel: result[3] as String?,
      currency: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RustoreProductSubscriptionPeriod ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RustorePurchase {
  RustorePurchase({
    required this.purchaseId,
    required this.purchaseType,
    required this.productType,
    required this.purchaseStatus,
    this.productId,
    this.invoiceId,
    this.orderId,
    this.amountLabel,
    this.amount,
    this.currency,
    this.quantity,
    this.purchaseTime,
    this.developerPayload,
    this.subscriptionToken,
    this.sandbox,
  });

  String purchaseId;

  RustorePurchaseType purchaseType;

  RustoreProductType productType;

  RustorePurchaseStatus purchaseStatus;

  String? productId;

  String? invoiceId;

  String? orderId;

  String? amountLabel;

  int? amount;

  String? currency;

  int? quantity;

  String? purchaseTime;

  String? developerPayload;

  String? subscriptionToken;

  bool? sandbox;

  List<Object?> _toList() {
    return <Object?>[
      purchaseId,
      purchaseType,
      productType,
      purchaseStatus,
      productId,
      invoiceId,
      orderId,
      amountLabel,
      amount,
      currency,
      quantity,
      purchaseTime,
      developerPayload,
      subscriptionToken,
      sandbox,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RustorePurchase decode(Object result) {
    result as List<Object?>;
    return RustorePurchase(
      purchaseId: result[0]! as String,
      purchaseType: result[1]! as RustorePurchaseType,
      productType: result[2]! as RustoreProductType,
      purchaseStatus: result[3]! as RustorePurchaseStatus,
      productId: result[4] as String?,
      invoiceId: result[5] as String?,
      orderId: result[6] as String?,
      amountLabel: result[7] as String?,
      amount: result[8] as int?,
      currency: result[9] as String?,
      quantity: result[10] as int?,
      purchaseTime: result[11] as String?,
      developerPayload: result[12] as String?,
      subscriptionToken: result[13] as String?,
      sandbox: result[14] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RustorePurchase || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RustorePurchaseFilter {
  RustorePurchaseFilter({
    this.productId,
    this.productType,
    this.purchaseStatus,
    this.purchaseType,
  });

  String? productId;

  RustoreProductType? productType;

  RustorePurchaseStatus? purchaseStatus;

  RustorePurchaseType? purchaseType;

  List<Object?> _toList() {
    return <Object?>[productId, productType, purchaseStatus, purchaseType];
  }

  Object encode() {
    return _toList();
  }

  static RustorePurchaseFilter decode(Object result) {
    result as List<Object?>;
    return RustorePurchaseFilter(
      productId: result[0] as String?,
      productType: result[1] as RustoreProductType?,
      purchaseStatus: result[2] as RustorePurchaseStatus?,
      purchaseType: result[3] as RustorePurchaseType?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RustorePurchaseFilter || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RustoreProductPurchaseParams {
  RustoreProductPurchaseParams({
    required this.productId,
    this.quantity,
    this.orderId,
    this.developerPayload,
    this.appUserId,
    this.appUserEmail,
  });

  String productId;

  int? quantity;

  String? orderId;

  String? developerPayload;

  String? appUserId;

  String? appUserEmail;

  List<Object?> _toList() {
    return <Object?>[
      productId,
      quantity,
      orderId,
      developerPayload,
      appUserId,
      appUserEmail,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RustoreProductPurchaseParams decode(Object result) {
    result as List<Object?>;
    return RustoreProductPurchaseParams(
      productId: result[0]! as String,
      quantity: result[1] as int?,
      orderId: result[2] as String?,
      developerPayload: result[3] as String?,
      appUserId: result[4] as String?,
      appUserEmail: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RustoreProductPurchaseParams ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RustoreProductPurchaseResult {
  RustoreProductPurchaseResult({
    required this.resultType,
    this.purchase,
    this.error,
  });

  RustoreProductPurchaseResultType resultType;

  RustorePurchase? purchase;

  RustorePurchaseError? error;

  List<Object?> _toList() {
    return <Object?>[resultType, purchase, error];
  }

  Object encode() {
    return _toList();
  }

  static RustoreProductPurchaseResult decode(Object result) {
    result as List<Object?>;
    return RustoreProductPurchaseResult(
      resultType: result[0]! as RustoreProductPurchaseResultType,
      purchase: result[1] as RustorePurchase?,
      error: result[2] as RustorePurchaseError?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RustoreProductPurchaseResult ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RustorePurchaseError {
  RustorePurchaseError({
    required this.code,
    required this.message,
    this.description,
    this.purchase,
  });

  String code;

  String message;

  String? description;

  RustorePurchase? purchase;

  List<Object?> _toList() {
    return <Object?>[code, message, description, purchase];
  }

  Object encode() {
    return _toList();
  }

  static RustorePurchaseError decode(Object result) {
    result as List<Object?>;
    return RustorePurchaseError(
      code: result[0]! as String,
      message: result[1]! as String,
      description: result[2] as String?,
      purchase: result[3] as RustorePurchase?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RustorePurchaseError || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RustoreException {
  RustoreException({required this.type, required this.message, this.errorCode});

  RustoreExceptionType type;

  String message;

  String? errorCode;

  List<Object?> _toList() {
    return <Object?>[type, message, errorCode];
  }

  Object encode() {
    return _toList();
  }

  static RustoreException decode(Object result) {
    result as List<Object?>;
    return RustoreException(
      type: result[0]! as RustoreExceptionType,
      message: result[1]! as String,
      errorCode: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RustoreException || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is RustoreBillingTheme) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is RustorePurchaseAvailabilityStatus) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is RustoreProductStatus) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is RustoreProductType) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is RustoreSubscriptionPeriodType) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is RustorePurchaseType) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is RustorePurchaseStatus) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    } else if (value is RustorePreferredPurchaseType) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    } else if (value is RustoreProductPurchaseResultType) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    } else if (value is RustoreExceptionType) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    } else if (value is RustoreBillingConfig) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is RustorePurchaseAvailabilityResult) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is RustoreProduct) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is RustoreProductSubscriptionInfo) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is RustoreProductSubscriptionPeriod) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is RustorePurchase) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is RustorePurchaseFilter) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is RustoreProductPurchaseParams) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is RustoreProductPurchaseResult) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is RustorePurchaseError) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is RustoreException) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : RustoreBillingTheme.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null
            ? null
            : RustorePurchaseAvailabilityStatus.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : RustoreProductStatus.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : RustoreProductType.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null
            ? null
            : RustoreSubscriptionPeriodType.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : RustorePurchaseType.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : RustorePurchaseStatus.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null
            ? null
            : RustorePreferredPurchaseType.values[value];
      case 137:
        final value = readValue(buffer) as int?;
        return value == null
            ? null
            : RustoreProductPurchaseResultType.values[value];
      case 138:
        final value = readValue(buffer) as int?;
        return value == null ? null : RustoreExceptionType.values[value];
      case 139:
        return RustoreBillingConfig.decode(readValue(buffer)!);
      case 140:
        return RustorePurchaseAvailabilityResult.decode(readValue(buffer)!);
      case 141:
        return RustoreProduct.decode(readValue(buffer)!);
      case 142:
        return RustoreProductSubscriptionInfo.decode(readValue(buffer)!);
      case 143:
        return RustoreProductSubscriptionPeriod.decode(readValue(buffer)!);
      case 144:
        return RustorePurchase.decode(readValue(buffer)!);
      case 145:
        return RustorePurchaseFilter.decode(readValue(buffer)!);
      case 146:
        return RustoreProductPurchaseParams.decode(readValue(buffer)!);
      case 147:
        return RustoreProductPurchaseResult.decode(readValue(buffer)!);
      case 148:
        return RustorePurchaseError.decode(readValue(buffer)!);
      case 149:
        return RustoreException.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class RustoreBillingApi {
  /// Constructor for [RustoreBillingApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RustoreBillingApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize(RustoreBillingConfig config) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[config],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<RustorePurchaseAvailabilityResult> getPurchaseAvailability() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.getPurchaseAvailability$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as RustorePurchaseAvailabilityResult?)!;
    }
  }

  Future<bool> getUserAuthorizationStatus() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.getUserAuthorizationStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<List<RustoreProduct>> getProducts(List<String> productIds) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.getProducts$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[productIds],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<RustoreProduct>();
    }
  }

  Future<List<RustorePurchase>> getPurchases(
    RustorePurchaseFilter? filter,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.getPurchases$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[filter],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!
          .cast<RustorePurchase>();
    }
  }

  Future<RustorePurchase?> getPurchase(String purchaseId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.getPurchase$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[purchaseId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as RustorePurchase?);
    }
  }

  Future<RustoreProductPurchaseResult> purchase(
    RustoreProductPurchaseParams params,
    RustorePreferredPurchaseType preferredPurchaseType,
    RustoreBillingTheme sdkTheme,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.purchase$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[params, preferredPurchaseType, sdkTheme],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as RustoreProductPurchaseResult?)!;
    }
  }

  Future<RustoreProductPurchaseResult> purchaseTwoStep(
    RustoreProductPurchaseParams params,
    RustoreBillingTheme sdkTheme,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.purchaseTwoStep$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[params, sdkTheme],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as RustoreProductPurchaseResult?)!;
    }
  }

  Future<void> confirmTwoStepPurchase(
    String purchaseId,
    String? developerPayload,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.confirmTwoStepPurchase$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[purchaseId, developerPayload],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> cancelTwoStepPurchase(String purchaseId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.cancelTwoStepPurchase$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[purchaseId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class RustoreBillingCallbackApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onPurchaseResult(RustoreProductPurchaseResult result);

  void onPurchaseError(RustorePurchaseError error);

  static void setUp(
    RustoreBillingCallbackApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.rustore_billing_api.RustoreBillingCallbackApi.onPurchaseResult$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.rustore_billing_api.RustoreBillingCallbackApi.onPurchaseResult was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final RustoreProductPurchaseResult? arg_result =
              (args[0] as RustoreProductPurchaseResult?);
          assert(
            arg_result != null,
            'Argument for dev.flutter.pigeon.rustore_billing_api.RustoreBillingCallbackApi.onPurchaseResult was null, expected non-null RustoreProductPurchaseResult.',
          );
          try {
            api.onPurchaseResult(arg_result!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.rustore_billing_api.RustoreBillingCallbackApi.onPurchaseError$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.rustore_billing_api.RustoreBillingCallbackApi.onPurchaseError was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final RustorePurchaseError? arg_error =
              (args[0] as RustorePurchaseError?);
          assert(
            arg_error != null,
            'Argument for dev.flutter.pigeon.rustore_billing_api.RustoreBillingCallbackApi.onPurchaseError was null, expected non-null RustorePurchaseError.',
          );
          try {
            api.onPurchaseError(arg_error!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
