name: _
publish_to: none
environment:
  sdk: ^3.12.0
workspace:
  - pkgs/*
  - pkgs/xsoulspace_steamworks/example/
  - pkgs/xsoulspace_inference_gemma_flutter/example/
  - pkgs/universal_storage_sync/example/todo_file_app/
  - pkgs/universal_storage_sync/example/todo_git_app/

dependency_overrides:
  device_info_plus: 13.1.0
  meta: 1.19.0
  test_api: 0.7.13
  analyzer: 14.1.0
  intl: 0.20.3
