name: universal_storage_sync
description: A cross-platform Dart package providing unified API for file storage operations with support for local filesystem and Git-based version control.
version: 0.1.0
homepage: https://github.com/xsoulspace/universal_storage_sync

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  git: ^2.3.1
  github: ^9.25.0
  http: ^1.1.0
  path: ^1.8.3
  meta: ^1.9.1

dev_dependencies:
  test: ^1.24.0
  mockito: ^5.4.2
  build_runner: ^2.4.7
  lints: ^3.0.0
# For web support - add specific dependencies as needed
# dependency_overrides:
