get:
    flutter pub get

test:
    flutter test

analyze:
    flutter analyze

format:
    dart format .

publish-dry:
    flutter pub publish --dry-run

publish:
    flutter pub publish

gen-rewrite:
    flutter pub run build_runner build --delete-conflicting-outputs

gen:
    flutter pub run build_runner build
