name: xsoulspace_monetization_foundation
description: A Flutter package for managing in-app purchases, subscriptions, and
  advertisements across multiple platforms.
version: 0.8.0
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter
  is_dart_empty_or_not: ^0.2.3
  xsoulspace_foundation: ^0.2.0
  xsoulspace_monetization_ads_interface:
    path: ../xsoulspace_monetization_ads_interface
  xsoulspace_monetization_interface:
    path: ../xsoulspace_monetization_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.2
