name: xsoulspace_monetization_foundation
description: A Flutter package for managing in-app purchases, subscriptions, and
  advertisements across multiple platforms.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_rustore_billing: ^8.0.0
  freezed_annotation: ^3.0.0
  huawei_iap: ^6.13.0+302
  in_app_purchase: ^3.2.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  universal_io: ^2.2.2
  url_launcher: ^6.3.1
  xsoulspace_foundation: ^0.0.11
  yandex_mobileads: ^7.4.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  lints: ^5.1.1
  xsoulspace_lints: ^0.0.14

dependency_overrides:
  go_router: ^14.3.0
