name: xsoulspace_monetization_ads_yandex
description: A new Flutter package.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  yandex_mobileads: ^7.13.0
  xsoulspace_monetization_ads_interface:
    path: ../xsoulspace_monetization_ads_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.2
