name: rustore_billing_api
description: Flutter plugin for RuStore billing integration
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  pigeon: ^26.0.0
  xsoulspace_lints: ^0.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.xsoulspace.rustore_billing_api
        pluginClass: RustoreBillingApiPlugin
