name: xsoulspace_platform_monetization_bridge
description: Compatibility export layer for purchases and ads bridge packages.
version: 0.1.0-beta.1
homepage: https://github.com/xsoulspace/dart_flutter_packages/tree/main/pkgs/xsoulspace_platform_monetization_bridge
repository: https://github.com/xsoulspace/dart_flutter_packages
issue_tracker: https://github.com/xsoulspace/dart_flutter_packages/issues

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  xsoulspace_platform_ads_bridge:
    hosted:
      name: xsoulspace_platform_ads_bridge
      url: https://pub.xsoulspace.dev
    version: ^0.1.0-beta.1
  xsoulspace_platform_purchases_bridge:
    hosted:
      name: xsoulspace_platform_purchases_bridge
      url: https://pub.xsoulspace.dev
    version: ^0.1.0-beta.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.26.3
  lints: ^6.0.0
  xsoulspace_lints:
    hosted:
      name: xsoulspace_lints
      url: https://pub.xsoulspace.dev
    version: ^0.1.2
  xsoulspace_monetization_ads_interface:
    hosted:
      name: xsoulspace_monetization_ads_interface
      url: https://pub.xsoulspace.dev
    version: ^0.0.1
  xsoulspace_monetization_interface:
    hosted:
      name: xsoulspace_monetization_interface
      url: https://pub.xsoulspace.dev
    version: ^0.8.2
