// Autogenerated from Pigeon (v26.1.10), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsCloudKitAppleApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsCloudKitAppleApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsCloudKitAppleApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashCloudKitAppleApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashCloudKitAppleApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashCloudKitAppleApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct CloudKitAppleConfigData: Hashable {
  var containerId: String
  var environment: String
  var databaseScope: String
  var zoneName: String
  var recordType: String
  var maxInlineBytes: Int64
  var webApiToken: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CloudKitAppleConfigData? {
    let containerId = pigeonVar_list[0] as! String
    let environment = pigeonVar_list[1] as! String
    let databaseScope = pigeonVar_list[2] as! String
    let zoneName = pigeonVar_list[3] as! String
    let recordType = pigeonVar_list[4] as! String
    let maxInlineBytes = pigeonVar_list[5] as! Int64
    let webApiToken: String? = nilOrValue(pigeonVar_list[6])

    return CloudKitAppleConfigData(
      containerId: containerId,
      environment: environment,
      databaseScope: databaseScope,
      zoneName: zoneName,
      recordType: recordType,
      maxInlineBytes: maxInlineBytes,
      webApiToken: webApiToken
    )
  }
  func toList() -> [Any?] {
    return [
      containerId,
      environment,
      databaseScope,
      zoneName,
      recordType,
      maxInlineBytes,
      webApiToken,
    ]
  }
  static func == (lhs: CloudKitAppleConfigData, rhs: CloudKitAppleConfigData) -> Bool {
    return deepEqualsCloudKitAppleApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCloudKitAppleApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CloudKitAppleRecordData: Hashable {
  var recordName: String
  var path: String
  var content: String
  var checksum: String
  var size: Int64
  var updatedAtIso8601: String
  var changeTag: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CloudKitAppleRecordData? {
    let recordName = pigeonVar_list[0] as! String
    let path = pigeonVar_list[1] as! String
    let content = pigeonVar_list[2] as! String
    let checksum = pigeonVar_list[3] as! String
    let size = pigeonVar_list[4] as! Int64
    let updatedAtIso8601 = pigeonVar_list[5] as! String
    let changeTag: String? = nilOrValue(pigeonVar_list[6])

    return CloudKitAppleRecordData(
      recordName: recordName,
      path: path,
      content: content,
      checksum: checksum,
      size: size,
      updatedAtIso8601: updatedAtIso8601,
      changeTag: changeTag
    )
  }
  func toList() -> [Any?] {
    return [
      recordName,
      path,
      content,
      checksum,
      size,
      updatedAtIso8601,
      changeTag,
    ]
  }
  static func == (lhs: CloudKitAppleRecordData, rhs: CloudKitAppleRecordData) -> Bool {
    return deepEqualsCloudKitAppleApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCloudKitAppleApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CloudKitAppleDeltaData: Hashable {
  var updatedRecords: [CloudKitAppleRecordData]
  var deletedPaths: [String]
  var nextServerChangeToken: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CloudKitAppleDeltaData? {
    let updatedRecords = pigeonVar_list[0] as! [CloudKitAppleRecordData]
    let deletedPaths = pigeonVar_list[1] as! [String]
    let nextServerChangeToken: String? = nilOrValue(pigeonVar_list[2])

    return CloudKitAppleDeltaData(
      updatedRecords: updatedRecords,
      deletedPaths: deletedPaths,
      nextServerChangeToken: nextServerChangeToken
    )
  }
  func toList() -> [Any?] {
    return [
      updatedRecords,
      deletedPaths,
      nextServerChangeToken,
    ]
  }
  static func == (lhs: CloudKitAppleDeltaData, rhs: CloudKitAppleDeltaData) -> Bool {
    return deepEqualsCloudKitAppleApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCloudKitAppleApi(value: toList(), hasher: &hasher)
  }
}

private class CloudKitAppleApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return CloudKitAppleConfigData.fromList(self.readValue() as! [Any?])
    case 130:
      return CloudKitAppleRecordData.fromList(self.readValue() as! [Any?])
    case 131:
      return CloudKitAppleDeltaData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CloudKitAppleApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CloudKitAppleConfigData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? CloudKitAppleRecordData {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? CloudKitAppleDeltaData {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CloudKitAppleApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CloudKitAppleApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CloudKitAppleApiPigeonCodecWriter(data: data)
  }
}

class CloudKitAppleApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CloudKitAppleApiPigeonCodec(readerWriter: CloudKitAppleApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CloudKitAppleHostApi {
  func initialize(config: CloudKitAppleConfigData, completion: @escaping (Result<Void, Error>) -> Void)
  func fetchRecordByPath(path: String, completion: @escaping (Result<CloudKitAppleRecordData?, Error>) -> Void)
  func saveRecord(record: CloudKitAppleRecordData, completion: @escaping (Result<Void, Error>) -> Void)
  func deleteRecord(recordName: String, completion: @escaping (Result<Void, Error>) -> Void)
  func queryByPathPrefix(pathPrefix: String, completion: @escaping (Result<[CloudKitAppleRecordData], Error>) -> Void)
  func fetchChanges(serverChangeToken: String?, completion: @escaping (Result<CloudKitAppleDeltaData, Error>) -> Void)
  func dispose(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CloudKitAppleHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CloudKitAppleApiPigeonCodec.shared }
  /// Sets up an instance of `CloudKitAppleHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CloudKitAppleHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.universal_storage_cloudkit_apple.CloudKitAppleHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! CloudKitAppleConfigData
        api.initialize(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let fetchRecordByPathChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.universal_storage_cloudkit_apple.CloudKitAppleHostApi.fetchRecordByPath\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fetchRecordByPathChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        api.fetchRecordByPath(path: pathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      fetchRecordByPathChannel.setMessageHandler(nil)
    }
    let saveRecordChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.universal_storage_cloudkit_apple.CloudKitAppleHostApi.saveRecord\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveRecordChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let recordArg = args[0] as! CloudKitAppleRecordData
        api.saveRecord(record: recordArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveRecordChannel.setMessageHandler(nil)
    }
    let deleteRecordChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.universal_storage_cloudkit_apple.CloudKitAppleHostApi.deleteRecord\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteRecordChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let recordNameArg = args[0] as! String
        api.deleteRecord(recordName: recordNameArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteRecordChannel.setMessageHandler(nil)
    }
    let queryByPathPrefixChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.universal_storage_cloudkit_apple.CloudKitAppleHostApi.queryByPathPrefix\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queryByPathPrefixChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathPrefixArg = args[0] as! String
        api.queryByPathPrefix(pathPrefix: pathPrefixArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      queryByPathPrefixChannel.setMessageHandler(nil)
    }
    let fetchChangesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.universal_storage_cloudkit_apple.CloudKitAppleHostApi.fetchChanges\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fetchChangesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let serverChangeTokenArg: String? = nilOrValue(args[0])
        api.fetchChanges(serverChangeToken: serverChangeTokenArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      fetchChangesChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.universal_storage_cloudkit_apple.CloudKitAppleHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        api.dispose { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
