name: universal_storage_oauth
description: OAuth provider for Git platforms (GitHub, GitLab, etc.) with secure
  credential management
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0-beta.4
  from_json_to_json: ^0.2.0
  github: ^9.25.0
  http: ^1.4.0
  oauth2: ^2.0.3
  oauth2_client: ^4.2.0

dev_dependencies:
  build_runner: ^2.5.2
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  mockito: ^5.4.6
  xsoulspace_lints: ^0.1.0
