name: xsoulspace_platform_gamification_interface
description: Gamification capabilities for xsoulspace unified platform runtime.
version: 0.1.0-beta.1
homepage: https://github.com/xsoulspace/dart_flutter_packages/tree/main/pkgs/xsoulspace_platform_gamification_interface
repository: https://github.com/xsoulspace/dart_flutter_packages
issue_tracker: https://github.com/xsoulspace/dart_flutter_packages/issues

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  meta: ^1.16.0
  xsoulspace_platform_core_interface:
    hosted:
      name: xsoulspace_platform_core_interface
      url: https://pub.xsoulspace.dev
    version: ^0.1.0-beta.1
dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  xsoulspace_lints:
    hosted:
      name: xsoulspace_lints
      url: https://pub.xsoulspace.dev
    version: ^0.1.2
