name: xsoulspace_monetization_interface
description: A new Flutter package.
version: 0.3.0
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  from_json_to_json: ^0.2.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  freezed: ^3.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
