name: xsoulspace_monetization_interface
description: Common interfaces for xsoulspace_monetization_foundation.
version: 0.6.0
homepage: https://github.com/xsoulspace/dart_flutter_packages/tree/main/pkgs/xsoulspace_monetization_interface
repository: https://github.com/xsoulspace/dart_flutter_packages

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  from_json_to_json: ^0.3.0
  is_dart_empty_or_not: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.2
