name: universal_storage_cloudkit_web
description: Web CloudKit JS bridge for universal_storage_cloudkit.
version: 0.1.0-dev.1
homepage: https://github.com/xsoulspace/universal_storage_sync
repository: https://github.com/xsoulspace/universal_storage_sync
issue_tracker: https://github.com/xsoulspace/universal_storage_sync/issues

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  universal_storage_cloudkit_platform_interface: ^0.1.0-dev.1

dev_dependencies:
  lints: ^6.0.0
  path: ^1.9.1
  test: ^1.26.2
  xsoulspace_js_interop_codegen:
    path: ../xsoulspace_js_interop_codegen
  xsoulspace_lints: ^0.1.2
