name: xsoulspace_ui_foundation
description: Shared UI utils, extensions, and helpers.
version: 0.3.1
homepage: https://github.com/xsoulspace/dart_flutter_packages/tree/main/pkgs/xsoulspace_ui_foundation
repository: https://github.com/xsoulspace/dart_flutter_packages

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  from_json_to_json: ^0.3.0
  infinite_scroll_pagination: ^5.1.1
  is_dart_empty_or_not: ^0.2.3
  xsoulspace_foundation: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.2
