name: xsoulspace_review_google_apple
description: Google Play and Apple App Store review implementation for xsoulspace_review
version: 0.1.0
homepage: https://github.com/xsoulspace/dart_flutter_packages/tree/main/pkgs/xsoulspace_review_google_apple
repository: https://github.com/xsoulspace/dart_flutter_packages
issue_tracker: https://github.com/xsoulspace/xsoulspace_packages/issues

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  in_app_review: ^2.0.10
  xsoulspace_review_interface: ^0.4.0-beta.2

dev_dependencies:
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.2
