name: xsoulspace_monetization_ads_foundation
description: A Flutter package for managing advertisements across multiple platforms.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  universal_io: ^2.2.2
  url_launcher: ^6.3.1
  xsoulspace_foundation: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.0
