import 'dart:convert';
import 'dart:io';

import 'package:test/test.dart';
import 'package:xsoulspace_inference_mlx_native/xsoulspace_inference_mlx_native.dart';

/// The native engine against the reference laya-mlx runtime's recorded
/// outputs (16 parity cases, FP16 — test/fixtures/laya_golden_fp16.json,
/// generated by the pinned reference runtime on this machine).
///
/// Skips (honestly, with the reason) when the dylib or the weights are
/// absent; build them with tool/build_laya_native.sh after fetching
/// aac6fef/laya-mlx.
void main() {
  final goldenFile = File('test/fixtures/laya_golden_fp16.json');
  late List<dynamic> cases;

  setUpAll(() {
    if (goldenFile.existsSync()) {
      cases = jsonDecode(goldenFile.readAsStringSync()) as List<dynamic>;
    }
  });

  test('native engine reproduces the reference distributions', () async {
    if (!goldenFile.existsSync()) {
      return markTestSkipped('golden fixture absent');
    }
    final NativeLayaDecisionEngine engine;
    try {
      engine = await NativeLayaDecisionEngine.load();
    } on Object catch (error) {
      return markTestSkipped('native artifacts absent: $error');
    }
    addTearDown(engine.dispose);

    var questions = 0;
    var argmaxAgreements = 0;
    var maxProbError = 0.0;
    for (final rawCase in cases) {
      final golden = rawCase as Map<String, dynamic>;
      final decisions = engine.decideTyped(
        state: _serializeState(golden['state']),
        questions: {
          for (final entry
              in (golden['questions'] as Map).entries.cast<MapEntry<String, dynamic>>())
            entry.key: _typedQuestion(entry.value as Map<String, dynamic>),
        },
      );
      final answers = golden['answers'] as Map<String, dynamic>;
      for (final entry in answers.entries) {
        final expected = entry.value as Map<String, dynamic>;
        final actual = decisions[entry.key]!;
        questions++;

        switch (expected['type'] as String) {
          case 'choice':
            if (expected['choice'] == actual.choice) argmaxAgreements++;
          case 'score':
            final expectedScore = (expected['score'] as num).toDouble();
            if ((expectedScore - actual.score!).abs() < 0.02) {
              argmaxAgreements++;
            }
          case 'noul':
            final expectedNoul = (expected['noul'] as num).toDouble();
            if ((expectedNoul - actual.noul!).abs() < 0.02) {
              argmaxAgreements++;
            }
        }
        // The reference records probabilities for choice and score only.
        final expectedProbs = expected['probabilities'];
        if (expectedProbs is Map) {
          for (final prob in expectedProbs.entries) {
            maxProbError = maxDouble(
              maxProbError,
              ((prob.value as num).toDouble() - actual.probabilities[prob.key]!)
                  .abs(),
            );
          }
        }
      }
    }
    // Reference fidelity bar (validation.json): argmax agrees on every
    // question; FP16 probability drift stays far below the 2e-2 the
    // checkpoint's own validation tolerates against upstream FP32.
    expect(argmaxAgreements, questions,
        reason: 'agreements $argmaxAgreements/$questions');
    expect(maxProbError, lessThan(0.005),
        reason: 'max probability error $maxProbError');
    // ignore: avoid_print
    print('laya native parity: $argmaxAgreements/$questions, '
        'max prob error $maxProbError');
  }, timeout: const Timeout(Duration(minutes: 5)));
}

/// The reference serializes non-string states with `json.dumps(...,
/// ensure_ascii=False)` — the same rendering the Dart prompt builder uses.
String _serializeState(final Object? state) =>
    state is String ? state : renderLayaJson(state);

LayaTypedQuestion _typedQuestion(final Map<String, dynamic> definition) {
  final type = definition['type'] as String;
  final instructions = definition['instructions'];
  final instructionText = instructions is String
      ? instructions
      : renderLayaJson(instructions);
  switch (type) {
    case 'choice':
      final crit = definition['criteria'];
      return LayaTypedQuestion.choice(instructionText, {
        if (crit is Map)
          for (final entry in crit.entries.cast<MapEntry<dynamic, dynamic>>())
            '${entry.key}': renderLayaCriterion(
              entry.value == null || entry.value == '' ? '' : entry.value,
            )
        else
          for (final label in crit as List) '$label': '',
      });
    case 'score':
      return LayaTypedQuestion.score(
        instructionText,
        [
          for (final level in definition['criteria'] as List)
            renderLayaCriterion(level),
        ],
      );
    case 'noul':
      final crit = definition['criteria'];
      return LayaTypedQuestion.noul(
        instructionText,
        crit is Map
            ? {
                for (final entry in crit.entries.cast<MapEntry<dynamic, dynamic>>())
                  '${entry.key}': entry.value == null
                      ? ''
                      : renderLayaCriterion(entry.value),
              }
            : null,
      );  }
  throw FormatException('unknown golden question type $type');
}

double maxDouble(final double a, final double b) => a > b ? a : b;
