include: package:lints/recommended.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - require_trailing_commas
    - always_declare_return_types
    - avoid_print
