include: package:xsoulspace_lints/library.yaml

# Custom rules preserved from previous configuration
# Note: Most rules are already included in xsoulspace_lints/library.yaml
linter:
  rules:
    # Add custom overrides here if needed
