name: xsoulspace_logger
description: Generic configurable logger with console and file output support. Pure Dart package for reusable logging across projects.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
