name: xsoulspace_vkplay_js
description: Generated dart:js_interop bindings and Dart wrappers for VK Play iframe API.
version: 0.1.0-beta.1
repository: https://github.com/xsoulspace/dart_flutter_packages
homepage: https://github.com/xsoulspace/dart_flutter_packages/tree/main/pkgs/xsoulspace_vkplay_js
issue_tracker: https://github.com/xsoulspace/dart_flutter_packages/issues

topics:
  - vkplay
  - games
  - js-interop
  - web
  - xsoulspace

platforms:
  web:

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  meta: ^1.19.0
  xsoulspace_js_interop_runtime: ^0.1.0-dev.1

dev_dependencies:
  lints: ^6.1.0
  path: ^1.9.1
  test: ^1.31.2
  xsoulspace_js_interop_codegen: ^0.1.0-dev.1
  xsoulspace_lints: ^0.1.2
