name: xsoulspace_installation_store
description: Utilities for detecting install sources and targeting app stores across platforms.
version: 0.1.0
repository: https://github.com/xsoulspace/xsoulspace_packages
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  meta: ^1.16.0
  web: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.0
