name: xsoulspace_installation_store
description: Utilities for targeting app stores across platforms.
version: 0.1.1
repository: https://github.com/xsoulspace/xsoulspace_packages

homepage: https://github.com/xsoulspace/xsoulspace_packages/tree/main/pkgs/xsoulspace_installation_store
issue_tracker: https://github.com/xsoulspace/xsoulspace_packages/issues

topics:
  - install-source
  - app-store
  - store-detection
  - platform
  - xsoulspace

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  meta: ^1.16.0
  web: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.2
