default:
    @just --list

generate:
    dart run tool/generate.dart

generate-check:
    dart run tool/generate.dart --check

generate-bump:
    dart run tool/generate.dart --bump

analyze:
    dart analyze

test:
    dart test

verify:
    just generate-check
    just analyze
    just test
