name: xsoulspace_support
description: A reusable Flutter package for email support functionality
version: 0.1.0
homepage: https://github.com/xsoulspace/xsoulspace_support

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  xsoulspace_lints: ^0.1.0
  lints: ^3.0.0

flutter:
  uses-material-design: true
