name: xsoulspace_review
description: Foundation package for xsoulspace_review with core orchestration and UI
version: 0.4.0-beta.2
homepage: https://github.com/xsoulspace/dart_flutter_packages/tree/main/pkgs/xsoulspace_review
repository: https://github.com/xsoulspace/dart_flutter_packages
issue_tracker: https://github.com/xsoulspace/xsoulspace_packages/issues

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  url_launcher: ^6.3.2
  wiredash: ^2.5.0
  xsoulspace_foundation: ^0.3.0
  xsoulspace_locale: ^0.3.3
  xsoulspace_logger: ^0.2.0-beta.1
  xsoulspace_review_interface: ^0.4.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.2
