name: xsoulspace_review
description: Useful tools for review for stores (via plugins) and user feedback (via Wiredash)
version: 0.3.0-beta.4
homepage: https://github.com/xsoulspace/dart_flutter_packages/tree/main/pkgs/xsoulspace_review
repository: https://github.com/xsoulspace/dart_flutter_packages
issue_tracker: https://github.com/xsoulspace/xsoulspace_packages/issues

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rustore_review: ^9.1.0
  in_app_review: ^2.0.10
  meta: ^1.16.0
  universal_io: ^2.2.2
  url_launcher: ^6.3.2
  wiredash: ^2.5.0
  xsoulspace_foundation: ^0.2.0
  xsoulspace_installation_store: ^0.1.0
  xsoulspace_locale: ^0.3.0

dev_dependencies:
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.2
