name: xsoulspace_review
description: Useful tools for review for stores and user feedback
version: 0.2.1
homepage: https://github.com/xsoulspace/dart_flutter_packages/tree/main/pkgs/xsoulspace_review
repository: https://github.com/xsoulspace/dart_flutter_packages

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rustore_review: ^9.0.2
  in_app_review: ^2.0.10
  meta: ^1.16.0
  universal_io: ^2.2.2
  url_launcher: ^6.3.1
  wiredash: ^2.5.0
  xsoulspace_foundation: ^0.2.0
  xsoulspace_locale: ^0.2.0

dev_dependencies:
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.0
