name: xsoulspace_monetization_ads_interface
description: Core interfaces for xsoulspace ads monetization providers.
version: 0.0.1
homepage: https://github.com/xsoulspace/dart_flutter_packages/tree/main/pkgs/xsoulspace_monetization_ads_interface
repository: https://github.com/xsoulspace/dart_flutter_packages
issue_tracker: https://github.com/xsoulspace/dart_flutter_packages/issues

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  xsoulspace_lints:
    hosted:
      name: xsoulspace_lints
      url: https://pub.xsoulspace.dev
    version: ^0.1.2
