include: package:xsoulspace_lints/public_library.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "example/**"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
