name: universal_storage_sync
description: A cross-platform Dart package providing unified API for file
  storage operations with support for local filesystem and Git-based version
  control.
version: 0.1.0-dev.3
homepage: https://github.com/xsoulspace/universal_storage_sync
publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  universal_storage_interface:
    path: ../universal_storage_interface
  universal_storage_filesystem:
    path: ../universal_storage_filesystem
  universal_storage_github_api:
    path: ../universal_storage_github_api
  universal_storage_git_offline:
    path: ../universal_storage_git_offline

dev_dependencies:
  build_runner: ^2.5.2
  lints: ^6.0.0
  mockito: ^5.4.6
  test: ^1.26.2
  xsoulspace_lints: ^0.1.0
# For web support - add specific dependencies as needed
# dependency_overrides:
