name: universal_storage_sync
description: |
  A cross-platform Dart package providing unified API for file
  storage operations with support for local filesystem and Git-based
  control.
version: 0.1.0-dev.4
homepage: https://github.com/xsoulspace/universal_storage_sync
repository: https://github.com/xsoulspace/universal_storage_sync
issue_tracker: https://github.com/xsoulspace/universal_storage_sync/issues
documentation: https://github.com/xsoulspace/universal_storage_sync/tree/main/pkgs/universal_storage_sync

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  universal_storage_interface: ^0.1.0-dev.3
  from_json_to_json: ^0.2.1

dev_dependencies:
  build_runner: ^2.5.2
  lints: ^6.0.0
  mockito: ^5.4.6
  test: ^1.26.2
  xsoulspace_lints: ^0.1.0
