name: universal_storage_sync
description: |
  A cross-platform Dart package providing unified API for file
  storage operations with support for local filesystem and Git-based
  control.
version: 0.1.0-dev.11
homepage: https://github.com/xsoulspace/universal_storage_sync
repository: https://github.com/xsoulspace/universal_storage_sync
issue_tracker: https://github.com/xsoulspace/universal_storage_sync/issues
documentation: https://github.com/xsoulspace/universal_storage_sync/tree/main/pkgs/universal_storage_sync

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  from_json_to_json: ">=0.2.0 <0.5.0"
  is_dart_empty_or_not: ">=0.2.0 <0.5.0"
  meta: ^1.17.0
  universal_storage_interface:
    hosted:
      name: universal_storage_interface
      url: https://pub.xsoulspace.dev
    version: ^0.1.0-dev.11
dev_dependencies:
  build_runner: ^2.5.2
  lints: ^6.0.0
  mockito: ^5.4.6
  test: ^1.26.2
  universal_io: ^2.3.1
  universal_storage_cloudkit:
    hosted:
      name: universal_storage_cloudkit
      url: https://pub.xsoulspace.dev
    version: ^0.1.0-dev.1
  xsoulspace_lints:
    hosted:
      name: xsoulspace_lints
      url: https://pub.xsoulspace.dev
    version: ^0.1.2
