name: universal_storage_sync
description: A cross-platform Dart package providing unified API for file storage operations with support for local filesystem and Git-based version control.
version: 0.1.0-dev.1
homepage: https://github.com/xsoulspace/universal_storage_sync

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  git: ^2.3.1
  github: ^9.25.0
  http: ^1.4.0
  path: ^1.9.1
  meta: ^1.16.0
  retry: ^3.1.2
  from_json_to_json: ^0.2.0

dev_dependencies:
  test: ^1.26.2
  mockito: ^5.4.6
  build_runner: ^2.5.2
  lints: ^6.0.0
  xsoulspace_lints: ^0.1.0
# For web support - add specific dependencies as needed
# dependency_overrides:
