// Autogenerated from Pigeon (v26.1.10), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every(
          (MapEntry<Object?, Object?> entry) =>
              (b as Map<Object?, Object?>).containsKey(entry.key) &&
              _deepEquals(entry.value, b[entry.key]),
        );
  }
  return a == b;
}

class CloudKitAppleConfigData {
  CloudKitAppleConfigData({
    required this.containerId,
    required this.environment,
    required this.databaseScope,
    required this.zoneName,
    required this.recordType,
    required this.maxInlineBytes,
    this.webApiToken,
  });

  String containerId;

  String environment;

  String databaseScope;

  String zoneName;

  String recordType;

  int maxInlineBytes;

  String? webApiToken;

  List<Object?> _toList() {
    return <Object?>[
      containerId,
      environment,
      databaseScope,
      zoneName,
      recordType,
      maxInlineBytes,
      webApiToken,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CloudKitAppleConfigData decode(Object result) {
    result as List<Object?>;
    return CloudKitAppleConfigData(
      containerId: result[0]! as String,
      environment: result[1]! as String,
      databaseScope: result[2]! as String,
      zoneName: result[3]! as String,
      recordType: result[4]! as String,
      maxInlineBytes: result[5]! as int,
      webApiToken: result[6] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CloudKitAppleConfigData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class CloudKitAppleRecordData {
  CloudKitAppleRecordData({
    required this.recordName,
    required this.path,
    required this.content,
    required this.checksum,
    required this.size,
    required this.updatedAtIso8601,
    this.changeTag,
  });

  String recordName;

  String path;

  String content;

  String checksum;

  int size;

  String updatedAtIso8601;

  String? changeTag;

  List<Object?> _toList() {
    return <Object?>[
      recordName,
      path,
      content,
      checksum,
      size,
      updatedAtIso8601,
      changeTag,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CloudKitAppleRecordData decode(Object result) {
    result as List<Object?>;
    return CloudKitAppleRecordData(
      recordName: result[0]! as String,
      path: result[1]! as String,
      content: result[2]! as String,
      checksum: result[3]! as String,
      size: result[4]! as int,
      updatedAtIso8601: result[5]! as String,
      changeTag: result[6] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CloudKitAppleRecordData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class CloudKitAppleDeltaData {
  CloudKitAppleDeltaData({
    this.updatedRecords = const <CloudKitAppleRecordData>[],
    this.deletedPaths = const <String>[],
    this.nextServerChangeToken,
  });

  List<CloudKitAppleRecordData> updatedRecords;

  List<String> deletedPaths;

  String? nextServerChangeToken;

  List<Object?> _toList() {
    return <Object?>[updatedRecords, deletedPaths, nextServerChangeToken];
  }

  Object encode() {
    return _toList();
  }

  static CloudKitAppleDeltaData decode(Object result) {
    result as List<Object?>;
    return CloudKitAppleDeltaData(
      updatedRecords: (result[0] as List<Object?>?)!
          .cast<CloudKitAppleRecordData>(),
      deletedPaths: (result[1] as List<Object?>?)!.cast<String>(),
      nextServerChangeToken: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CloudKitAppleDeltaData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is CloudKitAppleConfigData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is CloudKitAppleRecordData) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is CloudKitAppleDeltaData) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return CloudKitAppleConfigData.decode(readValue(buffer)!);
      case 130:
        return CloudKitAppleRecordData.decode(readValue(buffer)!);
      case 131:
        return CloudKitAppleDeltaData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class CloudKitAppleHostApi {
  /// Constructor for [CloudKitAppleHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CloudKitAppleHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize(CloudKitAppleConfigData config) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.universal_storage_cloudkit_apple.CloudKitAppleHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[config],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<CloudKitAppleRecordData?> fetchRecordByPath(String path) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.universal_storage_cloudkit_apple.CloudKitAppleHostApi.fetchRecordByPath$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[path],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as CloudKitAppleRecordData?;
  }

  Future<void> saveRecord(CloudKitAppleRecordData record) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.universal_storage_cloudkit_apple.CloudKitAppleHostApi.saveRecord$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[record],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> deleteRecord(String recordName) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.universal_storage_cloudkit_apple.CloudKitAppleHostApi.deleteRecord$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[recordName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<List<CloudKitAppleRecordData>> queryByPathPrefix(
    String pathPrefix,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.universal_storage_cloudkit_apple.CloudKitAppleHostApi.queryByPathPrefix$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[pathPrefix],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    )!;
    return (pigeonVar_replyValue as List<Object?>)
        .cast<CloudKitAppleRecordData>();
  }

  Future<CloudKitAppleDeltaData> fetchChanges(String? serverChangeToken) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.universal_storage_cloudkit_apple.CloudKitAppleHostApi.fetchChanges$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[serverChangeToken],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    )!;
    return pigeonVar_replyValue as CloudKitAppleDeltaData;
  }

  Future<void> dispose() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.universal_storage_cloudkit_apple.CloudKitAppleHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
