name: xsoulspace_monetization_yandex_games
description: Yandex Games purchase provider for xsoulspace monetization contracts.
version: 0.1.0
publish_to: none
homepage: https://github.com/xsoulspace/dart_flutter_packages/tree/main/pkgs/xsoulspace_monetization_yandex_games
repository: https://github.com/xsoulspace/dart_flutter_packages
issue_tracker: https://github.com/xsoulspace/dart_flutter_packages/issues

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  xsoulspace_monetization_interface:
    path: ../xsoulspace_monetization_interface
  xsoulspace_ysdk_games_js:
    path: ../xsoulspace_ysdk_games_js

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  xsoulspace_lints: ^0.1.2
