// Autogenerated from Pigeon (v26.1.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.xsoulspace.rustore_billing_api

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object RustoreApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class RustoreBillingTheme(val raw: Int) {
  LIGHT(0),
  DARK(1),
  SYSTEM(2),
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): RustoreBillingTheme? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class RustorePurchaseAvailabilityStatus(val raw: Int) {
  AVAILABLE(0),
  UNAVAILABLE(1),
  UNKNOWN(2);

  companion object {
    fun ofRaw(raw: Int): RustorePurchaseAvailabilityStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class RustoreProductStatus(val raw: Int) {
  ACTIVE(0),
  INACTIVE(1),
  UNKNOWN(2);

  companion object {
    fun ofRaw(raw: Int): RustoreProductStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class RustoreProductType(val raw: Int) {
  CONSUMABLE(0),
  NON_CONSUMABLE(1),
  SUBSCRIPTION(2),
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): RustoreProductType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class RustoreSubscriptionPeriodType(val raw: Int) {
  TRIAL(0),
  INTRO(1),
  MAIN(2),
  GRACE(3),
  HOLD(4),
  UNKNOWN(5);

  companion object {
    fun ofRaw(raw: Int): RustoreSubscriptionPeriodType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class RustorePurchaseType(val raw: Int) {
  ONE_STEP(0),
  TWO_STEP(1),
  UNDEFINED(2),
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): RustorePurchaseType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class RustorePurchaseStatus(val raw: Int) {
  CREATED(0),
  INVOICE_CREATED(1),
  PAID(2),
  CONFIRMED(3),
  CANCELLED(4),
  REVERSED(5),
  CONSUMED(6),
  CLOSED(7),
  ACTIVE(8),
  PAUSED(9),
  TERMINATED(10),
  UNKNOWN(11);

  companion object {
    fun ofRaw(raw: Int): RustorePurchaseStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class RustorePreferredPurchaseType(val raw: Int) {
  ONE_STEP(0),
  TWO_STEP(1),
  UNKNOWN(2);

  companion object {
    fun ofRaw(raw: Int): RustorePreferredPurchaseType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class RustoreProductPurchaseResultType(val raw: Int) {
  SUCCESS(0),
  CANCELLED(1),
  FAILURE(2),
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): RustoreProductPurchaseResultType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class RustoreExceptionType(val raw: Int) {
  NOT_INSTALLED(0),
  OUTDATED(1),
  USER_UNAUTHORIZED(2),
  GENERAL(3),
  UNKNOWN(4);

  companion object {
    fun ofRaw(raw: Int): RustoreExceptionType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RustoreBillingConfig (
  val consoleApplicationId: String,
  val deeplinkScheme: String,
  val debugLogs: Boolean,
  val defaultTheme: RustoreBillingTheme,
  val enableLogging: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RustoreBillingConfig {
      val consoleApplicationId = pigeonVar_list[0] as String
      val deeplinkScheme = pigeonVar_list[1] as String
      val debugLogs = pigeonVar_list[2] as Boolean
      val defaultTheme = pigeonVar_list[3] as RustoreBillingTheme
      val enableLogging = pigeonVar_list[4] as Boolean
      return RustoreBillingConfig(consoleApplicationId, deeplinkScheme, debugLogs, defaultTheme, enableLogging)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      consoleApplicationId,
      deeplinkScheme,
      debugLogs,
      defaultTheme,
      enableLogging,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RustoreBillingConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return RustoreApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RustorePurchaseAvailabilityResult (
  val status: RustorePurchaseAvailabilityStatus,
  val cause: RustoreException? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RustorePurchaseAvailabilityResult {
      val status = pigeonVar_list[0] as RustorePurchaseAvailabilityStatus
      val cause = pigeonVar_list[1] as RustoreException?
      return RustorePurchaseAvailabilityResult(status, cause)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      cause,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RustorePurchaseAvailabilityResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return RustoreApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RustoreProduct (
  val productId: String,
  val productType: RustoreProductType,
  val productStatus: RustoreProductStatus,
  val title: String? = null,
  val description: String? = null,
  val price: Long? = null,
  val priceLabel: String? = null,
  val currency: String? = null,
  val language: String? = null,
  val subscriptionInfo: RustoreProductSubscriptionInfo? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RustoreProduct {
      val productId = pigeonVar_list[0] as String
      val productType = pigeonVar_list[1] as RustoreProductType
      val productStatus = pigeonVar_list[2] as RustoreProductStatus
      val title = pigeonVar_list[3] as String?
      val description = pigeonVar_list[4] as String?
      val price = pigeonVar_list[5] as Long?
      val priceLabel = pigeonVar_list[6] as String?
      val currency = pigeonVar_list[7] as String?
      val language = pigeonVar_list[8] as String?
      val subscriptionInfo = pigeonVar_list[9] as RustoreProductSubscriptionInfo?
      return RustoreProduct(productId, productType, productStatus, title, description, price, priceLabel, currency, language, subscriptionInfo)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      productId,
      productType,
      productStatus,
      title,
      description,
      price,
      priceLabel,
      currency,
      language,
      subscriptionInfo,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RustoreProduct) {
      return false
    }
    if (this === other) {
      return true
    }
    return RustoreApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RustoreProductSubscriptionInfo (
  val periods: List<RustoreProductSubscriptionPeriod>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RustoreProductSubscriptionInfo {
      val periods = pigeonVar_list[0] as List<RustoreProductSubscriptionPeriod>
      return RustoreProductSubscriptionInfo(periods)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      periods,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RustoreProductSubscriptionInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return RustoreApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RustoreProductSubscriptionPeriod (
  val type: RustoreSubscriptionPeriodType,
  val durationIso: String,
  val price: Long? = null,
  val priceLabel: String? = null,
  val currency: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RustoreProductSubscriptionPeriod {
      val type = pigeonVar_list[0] as RustoreSubscriptionPeriodType
      val durationIso = pigeonVar_list[1] as String
      val price = pigeonVar_list[2] as Long?
      val priceLabel = pigeonVar_list[3] as String?
      val currency = pigeonVar_list[4] as String?
      return RustoreProductSubscriptionPeriod(type, durationIso, price, priceLabel, currency)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      durationIso,
      price,
      priceLabel,
      currency,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RustoreProductSubscriptionPeriod) {
      return false
    }
    if (this === other) {
      return true
    }
    return RustoreApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RustorePurchase (
  val purchaseId: String,
  val purchaseType: RustorePurchaseType,
  val productType: RustoreProductType,
  val purchaseStatus: RustorePurchaseStatus,
  val productId: String? = null,
  val invoiceId: String? = null,
  val orderId: String? = null,
  val amountLabel: String? = null,
  val amount: Long? = null,
  val currency: String? = null,
  val quantity: Long? = null,
  val purchaseTime: String? = null,
  val developerPayload: String? = null,
  val subscriptionToken: String? = null,
  val sandbox: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RustorePurchase {
      val purchaseId = pigeonVar_list[0] as String
      val purchaseType = pigeonVar_list[1] as RustorePurchaseType
      val productType = pigeonVar_list[2] as RustoreProductType
      val purchaseStatus = pigeonVar_list[3] as RustorePurchaseStatus
      val productId = pigeonVar_list[4] as String?
      val invoiceId = pigeonVar_list[5] as String?
      val orderId = pigeonVar_list[6] as String?
      val amountLabel = pigeonVar_list[7] as String?
      val amount = pigeonVar_list[8] as Long?
      val currency = pigeonVar_list[9] as String?
      val quantity = pigeonVar_list[10] as Long?
      val purchaseTime = pigeonVar_list[11] as String?
      val developerPayload = pigeonVar_list[12] as String?
      val subscriptionToken = pigeonVar_list[13] as String?
      val sandbox = pigeonVar_list[14] as Boolean?
      return RustorePurchase(purchaseId, purchaseType, productType, purchaseStatus, productId, invoiceId, orderId, amountLabel, amount, currency, quantity, purchaseTime, developerPayload, subscriptionToken, sandbox)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      purchaseId,
      purchaseType,
      productType,
      purchaseStatus,
      productId,
      invoiceId,
      orderId,
      amountLabel,
      amount,
      currency,
      quantity,
      purchaseTime,
      developerPayload,
      subscriptionToken,
      sandbox,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RustorePurchase) {
      return false
    }
    if (this === other) {
      return true
    }
    return RustoreApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RustorePurchaseFilter (
  val productId: String? = null,
  val productType: RustoreProductType? = null,
  val purchaseStatus: RustorePurchaseStatus? = null,
  val purchaseType: RustorePurchaseType? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RustorePurchaseFilter {
      val productId = pigeonVar_list[0] as String?
      val productType = pigeonVar_list[1] as RustoreProductType?
      val purchaseStatus = pigeonVar_list[2] as RustorePurchaseStatus?
      val purchaseType = pigeonVar_list[3] as RustorePurchaseType?
      return RustorePurchaseFilter(productId, productType, purchaseStatus, purchaseType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      productId,
      productType,
      purchaseStatus,
      purchaseType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RustorePurchaseFilter) {
      return false
    }
    if (this === other) {
      return true
    }
    return RustoreApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RustoreProductPurchaseParams (
  val productId: String,
  val quantity: Long? = null,
  val orderId: String? = null,
  val developerPayload: String? = null,
  val appUserId: String? = null,
  val appUserEmail: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RustoreProductPurchaseParams {
      val productId = pigeonVar_list[0] as String
      val quantity = pigeonVar_list[1] as Long?
      val orderId = pigeonVar_list[2] as String?
      val developerPayload = pigeonVar_list[3] as String?
      val appUserId = pigeonVar_list[4] as String?
      val appUserEmail = pigeonVar_list[5] as String?
      return RustoreProductPurchaseParams(productId, quantity, orderId, developerPayload, appUserId, appUserEmail)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      productId,
      quantity,
      orderId,
      developerPayload,
      appUserId,
      appUserEmail,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RustoreProductPurchaseParams) {
      return false
    }
    if (this === other) {
      return true
    }
    return RustoreApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RustoreProductPurchaseResult (
  val resultType: RustoreProductPurchaseResultType,
  val purchase: RustorePurchase? = null,
  val error: RustorePurchaseError? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RustoreProductPurchaseResult {
      val resultType = pigeonVar_list[0] as RustoreProductPurchaseResultType
      val purchase = pigeonVar_list[1] as RustorePurchase?
      val error = pigeonVar_list[2] as RustorePurchaseError?
      return RustoreProductPurchaseResult(resultType, purchase, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      resultType,
      purchase,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RustoreProductPurchaseResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return RustoreApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RustorePurchaseError (
  val code: String,
  val message: String,
  val description: String? = null,
  val purchase: RustorePurchase? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RustorePurchaseError {
      val code = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      val description = pigeonVar_list[2] as String?
      val purchase = pigeonVar_list[3] as RustorePurchase?
      return RustorePurchaseError(code, message, description, purchase)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
      description,
      purchase,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RustorePurchaseError) {
      return false
    }
    if (this === other) {
      return true
    }
    return RustoreApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RustoreException (
  val type: RustoreExceptionType,
  val message: String,
  val errorCode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RustoreException {
      val type = pigeonVar_list[0] as RustoreExceptionType
      val message = pigeonVar_list[1] as String
      val errorCode = pigeonVar_list[2] as String?
      return RustoreException(type, message, errorCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      message,
      errorCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RustoreException) {
      return false
    }
    if (this === other) {
      return true
    }
    return RustoreApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class RustoreApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RustoreBillingTheme.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RustorePurchaseAvailabilityStatus.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RustoreProductStatus.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RustoreProductType.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RustoreSubscriptionPeriodType.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RustorePurchaseType.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RustorePurchaseStatus.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RustorePreferredPurchaseType.ofRaw(it.toInt())
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RustoreProductPurchaseResultType.ofRaw(it.toInt())
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RustoreExceptionType.ofRaw(it.toInt())
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RustoreBillingConfig.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RustorePurchaseAvailabilityResult.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RustoreProduct.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RustoreProductSubscriptionInfo.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RustoreProductSubscriptionPeriod.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RustorePurchase.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RustorePurchaseFilter.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RustoreProductPurchaseParams.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RustoreProductPurchaseResult.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RustorePurchaseError.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RustoreException.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is RustoreBillingTheme -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is RustorePurchaseAvailabilityStatus -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is RustoreProductStatus -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is RustoreProductType -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is RustoreSubscriptionPeriodType -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is RustorePurchaseType -> {
        stream.write(134)
        writeValue(stream, value.raw.toLong())
      }
      is RustorePurchaseStatus -> {
        stream.write(135)
        writeValue(stream, value.raw.toLong())
      }
      is RustorePreferredPurchaseType -> {
        stream.write(136)
        writeValue(stream, value.raw.toLong())
      }
      is RustoreProductPurchaseResultType -> {
        stream.write(137)
        writeValue(stream, value.raw.toLong())
      }
      is RustoreExceptionType -> {
        stream.write(138)
        writeValue(stream, value.raw.toLong())
      }
      is RustoreBillingConfig -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is RustorePurchaseAvailabilityResult -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is RustoreProduct -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is RustoreProductSubscriptionInfo -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is RustoreProductSubscriptionPeriod -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is RustorePurchase -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is RustorePurchaseFilter -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is RustoreProductPurchaseParams -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is RustoreProductPurchaseResult -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is RustorePurchaseError -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is RustoreException -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface RustoreBillingApi {
  fun initialize(config: RustoreBillingConfig, callback: (Result<Unit>) -> Unit)
  fun getPurchaseAvailability(callback: (Result<RustorePurchaseAvailabilityResult>) -> Unit)
  fun getUserAuthorizationStatus(callback: (Result<Boolean>) -> Unit)
  fun getProducts(productIds: List<String>, callback: (Result<List<RustoreProduct>>) -> Unit)
  fun getPurchases(filter: RustorePurchaseFilter?, callback: (Result<List<RustorePurchase>>) -> Unit)
  fun getPurchase(purchaseId: String, callback: (Result<RustorePurchase?>) -> Unit)
  fun purchase(params: RustoreProductPurchaseParams, preferredPurchaseType: RustorePreferredPurchaseType, sdkTheme: RustoreBillingTheme, callback: (Result<RustoreProductPurchaseResult>) -> Unit)
  fun purchaseTwoStep(params: RustoreProductPurchaseParams, sdkTheme: RustoreBillingTheme, callback: (Result<RustoreProductPurchaseResult>) -> Unit)
  fun confirmTwoStepPurchase(purchaseId: String, developerPayload: String?, callback: (Result<Unit>) -> Unit)
  fun cancelTwoStepPurchase(purchaseId: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by RustoreBillingApi. */
    val codec: MessageCodec<Any?> by lazy {
      RustoreApiPigeonCodec()
    }
    /** Sets up an instance of `RustoreBillingApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: RustoreBillingApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as RustoreBillingConfig
            api.initialize(configArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RustoreApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(RustoreApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.getPurchaseAvailability$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getPurchaseAvailability{ result: Result<RustorePurchaseAvailabilityResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RustoreApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(RustoreApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.getUserAuthorizationStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getUserAuthorizationStatus{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RustoreApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(RustoreApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.getProducts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val productIdsArg = args[0] as List<String>
            api.getProducts(productIdsArg) { result: Result<List<RustoreProduct>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RustoreApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(RustoreApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.getPurchases$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filterArg = args[0] as RustorePurchaseFilter?
            api.getPurchases(filterArg) { result: Result<List<RustorePurchase>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RustoreApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(RustoreApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.getPurchase$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val purchaseIdArg = args[0] as String
            api.getPurchase(purchaseIdArg) { result: Result<RustorePurchase?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RustoreApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(RustoreApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.purchase$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramsArg = args[0] as RustoreProductPurchaseParams
            val preferredPurchaseTypeArg = args[1] as RustorePreferredPurchaseType
            val sdkThemeArg = args[2] as RustoreBillingTheme
            api.purchase(paramsArg, preferredPurchaseTypeArg, sdkThemeArg) { result: Result<RustoreProductPurchaseResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RustoreApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(RustoreApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.purchaseTwoStep$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramsArg = args[0] as RustoreProductPurchaseParams
            val sdkThemeArg = args[1] as RustoreBillingTheme
            api.purchaseTwoStep(paramsArg, sdkThemeArg) { result: Result<RustoreProductPurchaseResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RustoreApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(RustoreApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.confirmTwoStepPurchase$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val purchaseIdArg = args[0] as String
            val developerPayloadArg = args[1] as String?
            api.confirmTwoStepPurchase(purchaseIdArg, developerPayloadArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RustoreApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(RustoreApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rustore_billing_api.RustoreBillingApi.cancelTwoStepPurchase$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val purchaseIdArg = args[0] as String
            api.cancelTwoStepPurchase(purchaseIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RustoreApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(RustoreApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class RustoreBillingCallbackApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by RustoreBillingCallbackApi. */
    val codec: MessageCodec<Any?> by lazy {
      RustoreApiPigeonCodec()
    }
  }
  fun onPurchaseResult(resultArg: RustoreProductPurchaseResult, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.rustore_billing_api.RustoreBillingCallbackApi.onPurchaseResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(resultArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(RustoreApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onPurchaseError(errorArg: RustorePurchaseError, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.rustore_billing_api.RustoreBillingCallbackApi.onPurchaseError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(RustoreApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
