name: xsoulspace_discord_js
description: Generated dart:js_interop bindings and Dart wrappers for Discord Embedded App SDK.
version: 0.1.0-beta.1
repository: https://github.com/xsoulspace/dart_flutter_packages
homepage: https://github.com/xsoulspace/dart_flutter_packages/tree/main/pkgs/xsoulspace_discord_js
issue_tracker: https://github.com/xsoulspace/dart_flutter_packages/issues

topics:
  - discord
  - activities
  - js-interop
  - web
  - xsoulspace

platforms:
  web:

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^6.0.0
  path: ^1.9.1
  test: ^1.26.3
  xsoulspace_js_interop_codegen:
    hosted:
      name: xsoulspace_js_interop_codegen
      url: https://pub.xsoulspace.dev
    version: ^0.1.0
  xsoulspace_lints:
    hosted:
      name: xsoulspace_lints
      url: https://pub.xsoulspace.dev
    version: ^0.1.2
