// lib/src/generator.dart
import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/type.dart';
import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

import 'annotations.dart';

class GenerableGenerator extends GeneratorForAnnotation<GenerableStruct> {
  @override
  Future<String> generateForAnnotatedElement(
    Element element,
    ConstantReader annotation,
    BuildStep buildStep,
  ) async {
    if (element is! ClassElement && element is! EnumElement) {
      throw InvalidGenerationSourceError(
        '@GenerableStruct can only be applied to classes or enums.',
        element: element,
      );
    }

    final buffer = StringBuffer();
    buffer.writeln('// Generated by generable_generator. Do not edit.');
    buffer.writeln('import Foundation');
    buffer.writeln('import FoundationModels'); // or whatever the real module is
    buffer.writeln();

    if (element is EnumElement) {
      _generateEnum(element, annotation, buffer);
    } else {
      _generateStruct(element as ClassElement, annotation, buffer);
    }

    return buffer.toString();
  }

  void _generateStruct(
    ClassElement element,
    ConstantReader annotation,
    StringBuffer buffer,
  ) {
    final swiftName = annotation.peek('name')?.stringValue ?? element.name;
    final description = annotation.peek('description')?.stringValue;

    buffer.writeln('@Generable');
    if (description != null) {
      buffer.writeln('// $description');
    }
    buffer.writeln('struct $swiftName {');

    for (final field in element.fields.where((f) => !f.isStatic)) {
      final guide = _readGuide(field);
      if (guide != null) {
        buffer.write('  ');
        _writeGuide(guide, buffer);
        buffer.writeln();
      }

      final type = _dartTypeToSwift(field.type);
      buffer.writeln('  let ${field.name}: $type');
    }

    buffer.writeln('}');
    buffer.writeln();
  }

  void _generateEnum(
    EnumElement element,
    ConstantReader annotation,
    StringBuffer buffer,
  ) {
    final swiftName = annotation.peek('name')?.stringValue ?? element.name;

    buffer.writeln('@Generable');
    buffer.writeln('enum $swiftName {');
    for (final value in element.constants) {
      buffer.writeln('  case ${value.name}');
    }
    buffer.writeln('}');
    buffer.writeln();
  }

  // --- helpers ----------------------------------------------------------

  GuideData? _readGuide(FieldElement field) {
    for (final meta in field.metadata.annotations) {
      final reader = ConstantReader(meta.computeConstantValue());
      if (reader.instanceOf(const TypeChecker.typeNamed(Guide))) {
        return GuideData(
          description: reader.peek('description')?.stringValue,
          range: reader
              .peek('range')
              ?.listValue
              .map((v) => v.toDoubleValue()!)
              .toList(),
          count: reader.peek('count')?.intValue,
          pattern: reader.peek('pattern')?.stringValue,
        );
      }
    }
    return null;
  }

  void _writeGuide(GuideData guide, StringBuffer buffer) {
    final parts = <String>[];
    if (guide.description != null) {
      parts.add('description: "${guide.description}"');
    }
    if (guide.range != null) {
      parts.add('.range(${guide.range![0]}...${guide.range![1]})');
    }
    if (guide.count != null) {
      parts.add('.count(${guide.count})');
    }
    if (guide.pattern != null) {
      parts.add('.pattern("${guide.pattern}")');
    }

    if (parts.isEmpty) {
      buffer.write('@Guide');
    } else if (parts.length == 1 && parts.first.startsWith('.')) {
      buffer.write('@Guide(${parts.first})');
    } else {
      buffer.write('@Guide(${parts.join(", ")})');
    }
  }

  String _dartTypeToSwift(DartType type) {
    // Extremely simplified – expand this properly
    if (type.isDartCoreString) return 'String';
    if (type.isDartCoreInt) return 'Int';
    if (type.isDartCoreDouble) return 'Double';
    if (type.isDartCoreBool) return 'Bool';
    if (type.isDartCoreList) {
      final arg = (type as ParameterizedType).typeArguments.first;
      return '[${_dartTypeToSwift(arg)}]';
    }
    return type.getDisplayString();
  }
}

class GuideData {
  GuideData({this.description, this.range, this.count, this.pattern});
  final String? description;
  final List<double>? range;
  final int? count;
  final String? pattern;
}
