import 'dart:async';
import 'dart:convert';

import 'package:path/path.dart' as path;
import 'package:universal_io/io.dart';
import 'package:universal_storage_interface/universal_storage_interface.dart';
import 'package:universal_storage_sync_utils/universal_storage_sync_utils.dart';

/// {@template filesystem_storage_provider}
/// A storage provider that uses the local file system for storage operations.
/// Supports both desktop/mobile (using dart:io).
///
/// This provider is not supported on web.
/// {@endtemplate}
class FileSystemStorageProvider extends StorageProvider implements LocalEngine {
  /// {@macro filesystem_storage_provider}
  FileSystemStorageProvider({this.maxReplayEntriesPerNamespace = 5000});

  static const _durabilitySchemaVersion = 1;
  static const _checkpointRetainedOperationIds = 2048;
  static const _rootNamespace = '_root';

  /// Bounded number of journal entries replayed during startup recovery.
  final int maxReplayEntriesPerNamespace;

  FileSystemConfig _config = FileSystemConfig.empty;
  String get _basePath => _config.basePath;
  var _isInitialized = false;
  Future<void> _mutationQueue = Future<void>.value();
  final Map<String, _DurabilityCheckpoint> _checkpointCache =
      <String, _DurabilityCheckpoint>{};

  Map<String, dynamic> _lastRecoveryReport = _emptyRecoveryReport();

  String get _usRootPath => path.join(_basePath, '.us');
  String get _journalRootPath => path.join(_usRootPath, 'journal');
  String get _checkpointRootPath => path.join(_usRootPath, 'checkpoints');
  String get _tmpRootPath => path.join(_usRootPath, 'tmp');
  String get _recoveryRootPath => path.join(_usRootPath, 'recovery');
  String get _recoveryReportPath =>
      path.join(_recoveryRootPath, 'last_recovery_report.json');

  /// Last startup recovery report generated by this provider.
  Map<String, dynamic> get lastRecoveryReport =>
      Map<String, dynamic>.from(_lastRecoveryReport);

  @override
  Future<void> initWithConfig(final StorageConfig config) async {
    if (config is! FileSystemConfig) {
      throw ArgumentError(
        'Expected FileSystemConfig, got ${config.runtimeType}',
      );
    }

    _config = config;

    final directory = await resolvePlatformDirectoryOfConfig(
      config.filePathConfig,
    );
    if (directory != null && !directory.existsSync()) {
      await directory.create(recursive: true);
    }
    await _ensureDurabilityDirectories();
    _checkpointCache.clear();
    _lastRecoveryReport = await _recoverFromJournal();
    _isInitialized = true;
  }

  @override
  Future<bool> isAuthenticated() async => _isInitialized;

  @override
  Future<FileOperationResult> createFile(
    final String filePath,
    final String content, {
    final String? commitMessage,
  }) => _enqueueMutation<FileOperationResult>(() async {
    _ensureInitialized();

    final relativePath = _normalizeRelativePath(filePath);
    final fullPath = path.join(_basePath, relativePath);
    final file = File(fullPath);
    if (file.existsSync()) {
      throw FileAlreadyExistsException(
        'File already exists at path: $filePath',
      );
    }

    final metadata = await _durableWrite(
      relativePath: relativePath,
      content: content,
      operationType: _DurabilityOperationType.create,
    );
    return FileOperationResult.created(path: fullPath, metadata: metadata);
  });

  @override
  Future<String?> getFile(final String filePath) async {
    _ensureInitialized();

    final relativePath = _normalizeRelativePath(filePath);
    final fullPath = path.join(_basePath, relativePath);
    final file = File(fullPath);

    if (!file.existsSync()) {
      return null;
    }

    try {
      return await file.readAsString();
    } catch (e) {
      throw NetworkException('Failed to read file at $filePath: $e');
    }
  }

  @override
  Future<FileOperationResult> updateFile(
    final String filePath,
    final String content, {
    final String? commitMessage,
  }) => _enqueueMutation<FileOperationResult>(() async {
    _ensureInitialized();

    final relativePath = _normalizeRelativePath(filePath);
    final fullPath = path.join(_basePath, relativePath);
    final file = File(fullPath);

    if (!file.existsSync()) {
      throw FileNotFoundException('File not found at path: $filePath');
    }

    final metadata = await _durableWrite(
      relativePath: relativePath,
      content: content,
      operationType: _DurabilityOperationType.update,
    );
    return FileOperationResult.updated(path: fullPath, metadata: metadata);
  });

  @override
  Future<FileOperationResult> deleteFile(
    final String filePath, {
    final String? commitMessage,
  }) => _enqueueMutation<FileOperationResult>(() async {
    _ensureInitialized();

    final relativePath = _normalizeRelativePath(filePath);
    final fullPath = path.join(_basePath, relativePath);
    final file = File(fullPath);
    if (!file.existsSync()) {
      throw FileNotFoundException('File not found at path: $filePath');
    }

    final metadata = await _durableDelete(relativePath: relativePath);
    return FileOperationResult.deleted(path: fullPath, metadata: metadata);
  });

  @override
  Future<List<FileEntry>> listDirectory(final String directoryPath) async {
    _ensureInitialized();

    final normalizedPath = directoryPath.trim().isEmpty
        ? '.'
        : directoryPath.trim();
    final fullPath = normalizedPath == '.'
        ? _basePath
        : path.join(_basePath, normalizedPath);
    final directory = Directory(fullPath);

    if (!directory.existsSync()) {
      return <FileEntry>[];
    }

    final entities = await directory.list().toList();
    final items = <FileEntry>[];
    for (final entity in entities) {
      final stat = await entity.stat();
      final name = path.relative(entity.path, from: _basePath);
      items.add(
        FileEntry(
          name: name,
          isDirectory: stat.type == FileSystemEntityType.directory,
          size: stat.size,
          modifiedAt: stat.modified,
        ),
      );
    }
    return items;
  }

  @override
  Future<void> restore(final String filePath, {final String? versionId}) {
    throw const UnsupportedOperationException(
      'Restore operation is not supported by FileSystemStorageProvider. '
      'Consider using OfflineGitStorageProvider for version control features.',
    );
  }

  @override
  bool get supportsSync => false;

  void _ensureInitialized() {
    if (!_isInitialized || _config.isEmpty) {
      throw const AuthenticationException(
        'Provider not initialized. Call init() first.',
      );
    }
  }

  @override
  Future<void> dispose() async {
    await _mutationQueue;
    _isInitialized = false;
    await disposePathOfFileConfig(_config.filePathConfig);
    _checkpointCache.clear();
    _lastRecoveryReport = _emptyRecoveryReport();
    _config = FileSystemConfig.empty;
  }

  Future<T> _enqueueMutation<T>(final Future<T> Function() action) {
    final completer = Completer<T>();
    _mutationQueue = _mutationQueue.then((_) async {
      try {
        completer.complete(await action());
      } catch (error, stackTrace) {
        completer.completeError(error, stackTrace);
      }
    });
    return completer.future;
  }

  Future<void> _ensureDurabilityDirectories() async {
    for (final directoryPath in <String>[
      _usRootPath,
      _journalRootPath,
      _checkpointRootPath,
      _tmpRootPath,
      _recoveryRootPath,
    ]) {
      final directory = Directory(directoryPath);
      if (!directory.existsSync()) {
        await directory.create(recursive: true);
      }
    }
  }

  Future<Map<String, dynamic>> _durableWrite({
    required final String relativePath,
    required final String content,
    required final _DurabilityOperationType operationType,
  }) async {
    final namespace = _namespaceForPath(relativePath);
    final checkpoint = await _loadCheckpoint(namespace);
    final sequence = checkpoint.lastSequence + 1;
    final operationId = _operationId(
      namespace: namespace,
      sequence: sequence,
      operationType: operationType,
    );
    final contentChecksum = normalizedSha256Hex(content);
    final tempRelativePath = _tempRelativePath(
      namespace: namespace,
      operationId: operationId,
    );
    final tempFullPath = path.join(_basePath, tempRelativePath);

    final tempFile = File(tempFullPath);
    if (!tempFile.parent.existsSync()) {
      await tempFile.parent.create(recursive: true);
    }
    await tempFile.writeAsString(content, flush: true);

    final preparedEntry = _DurabilityJournalEntry(
      schemaVersion: _durabilitySchemaVersion,
      namespace: namespace,
      operationId: operationId,
      sequence: sequence,
      operationType: operationType,
      stage: _DurabilityJournalStage.prepared,
      relativePath: relativePath,
      timestampUtc: DateTime.now().toUtc(),
      tempRelativePath: tempRelativePath,
      checksum: contentChecksum,
    );
    await _appendJournalEntry(preparedEntry);

    final targetFile = File(path.join(_basePath, relativePath));
    if (!targetFile.parent.existsSync()) {
      await targetFile.parent.create(recursive: true);
    }
    if (targetFile.existsSync()) {
      await targetFile.delete();
    }
    await tempFile.rename(targetFile.path);

    await _appendJournalEntry(
      preparedEntry.copyWith(stage: _DurabilityJournalStage.committed),
    );
    final updatedCheckpoint = checkpoint.markApplied(
      operationId: operationId,
      sequence: sequence,
      retainedOperationIds: _checkpointRetainedOperationIds,
    );
    await _persistCheckpoint(updatedCheckpoint);

    return <String, dynamic>{
      'durability_protocol': 'journal_v1',
      'durability_namespace': namespace,
      'durability_sequence': sequence,
      'durability_operation_id': operationId,
      'durability_checkpoint_sequence': updatedCheckpoint.lastSequence,
    };
  }

  Future<Map<String, dynamic>> _durableDelete({
    required final String relativePath,
  }) async {
    final namespace = _namespaceForPath(relativePath);
    final checkpoint = await _loadCheckpoint(namespace);
    final sequence = checkpoint.lastSequence + 1;
    final operationId = _operationId(
      namespace: namespace,
      sequence: sequence,
      operationType: _DurabilityOperationType.delete,
    );
    final targetFile = File(path.join(_basePath, relativePath));

    final preparedEntry = _DurabilityJournalEntry(
      schemaVersion: _durabilitySchemaVersion,
      namespace: namespace,
      operationId: operationId,
      sequence: sequence,
      operationType: _DurabilityOperationType.delete,
      stage: _DurabilityJournalStage.prepared,
      relativePath: relativePath,
      timestampUtc: DateTime.now().toUtc(),
      checksum: targetFile.existsSync()
          ? normalizedSha256Hex(await targetFile.readAsString())
          : '',
    );
    await _appendJournalEntry(preparedEntry);

    if (targetFile.existsSync()) {
      await targetFile.delete();
    }

    await _appendJournalEntry(
      preparedEntry.copyWith(stage: _DurabilityJournalStage.committed),
    );
    final updatedCheckpoint = checkpoint.markApplied(
      operationId: operationId,
      sequence: sequence,
      retainedOperationIds: _checkpointRetainedOperationIds,
    );
    await _persistCheckpoint(updatedCheckpoint);

    return <String, dynamic>{
      'durability_protocol': 'journal_v1',
      'durability_namespace': namespace,
      'durability_sequence': sequence,
      'durability_operation_id': operationId,
      'durability_checkpoint_sequence': updatedCheckpoint.lastSequence,
    };
  }

  Future<Map<String, dynamic>> _recoverFromJournal() async {
    final startedAt = DateTime.now().toUtc();
    final namespaceEntries = <String, List<_DurabilityJournalEntry>>{};
    final namespaceCorruptedCounts = <String, int>{};

    final journalDirectory = Directory(_journalRootPath);
    if (journalDirectory.existsSync()) {
      final entities = await journalDirectory.list().toList();
      for (final entity in entities.whereType<File>()) {
        final defaultNamespace = _namespaceFromJournalFile(entity.path);
        final lines = await entity.readAsLines();
        for (final line in lines) {
          if (line.trim().isEmpty) {
            continue;
          }
          final parsed = _DurabilityJournalEntry.tryParse(line);
          if (parsed == null) {
            namespaceCorruptedCounts[defaultNamespace] =
                (namespaceCorruptedCounts[defaultNamespace] ?? 0) + 1;
            continue;
          }
          namespaceEntries
              .putIfAbsent(parsed.namespace, () => <_DurabilityJournalEntry>[])
              .add(parsed);
        }
      }
    }

    var abnormalTerminationDetected = false;
    var totalReplayedOperations = 0;
    var totalRecoveredWrites = 0;
    var totalRecoveredDeletes = 0;
    var totalDuplicateSkips = 0;
    var totalCorrupted = 0;
    var totalTruncated = 0;
    final namespaceReports = <Map<String, dynamic>>[];

    final namespaces = <String>{
      ...namespaceEntries.keys,
      ...namespaceCorruptedCounts.keys,
    }.toList()..sort();

    for (final namespace in namespaces) {
      final rawEntries =
          namespaceEntries[namespace] ?? <_DurabilityJournalEntry>[];
      rawEntries.sort((final a, final b) => a.sequence.compareTo(b.sequence));

      var truncatedEntries = 0;
      final entries = rawEntries.length > maxReplayEntriesPerNamespace
          ? rawEntries
                .sublist(rawEntries.length - maxReplayEntriesPerNamespace)
                .toList(growable: false)
          : rawEntries.toList(growable: false);
      if (rawEntries.length > maxReplayEntriesPerNamespace) {
        truncatedEntries = rawEntries.length - entries.length;
      }

      final checkpoint = await _loadCheckpoint(namespace);
      final replayByOperationId = <String, _DurabilityReplayOperation>{};
      for (final entry in entries) {
        final replay = replayByOperationId.putIfAbsent(
          entry.operationId,
          () => _DurabilityReplayOperation(operationId: entry.operationId),
        );
        replay.track(entry);
      }

      final ordered = replayByOperationId.values.toList()
        ..sort((final a, final b) => a.sequence.compareTo(b.sequence));

      var namespaceReplayed = 0;
      var namespaceRecoveredWrites = 0;
      var namespaceRecoveredDeletes = 0;
      var namespaceDuplicateSkips = 0;
      final namespaceCorrupted = namespaceCorruptedCounts[namespace] ?? 0;
      final namespaceIssues = <String>[];
      var nextCheckpoint = checkpoint;

      for (final replay in ordered) {
        if (nextCheckpoint.appliedOperationIds.contains(replay.operationId)) {
          namespaceDuplicateSkips++;
          continue;
        }

        if (replay.committed) {
          nextCheckpoint = nextCheckpoint.markApplied(
            operationId: replay.operationId,
            sequence: replay.sequence,
            retainedOperationIds: _checkpointRetainedOperationIds,
          );
          namespaceDuplicateSkips++;
          continue;
        }

        final prepared = replay.preparedEntry;
        if (prepared == null) {
          continue;
        }
        abnormalTerminationDetected = true;

        var recovered = false;
        if (prepared.operationType == _DurabilityOperationType.delete) {
          recovered = await _recoverPreparedDelete(prepared);
          if (recovered) {
            namespaceRecoveredDeletes++;
          }
        } else {
          recovered = await _recoverPreparedWrite(prepared);
          if (recovered) {
            namespaceRecoveredWrites++;
          }
        }

        if (!recovered) {
          namespaceIssues.add(
            'Operation ${prepared.operationId} could not be recovered.',
          );
          continue;
        }

        await _appendJournalEntry(
          prepared.copyWith(
            stage: _DurabilityJournalStage.committed,
            recovered: true,
          ),
        );
        nextCheckpoint = nextCheckpoint.markApplied(
          operationId: prepared.operationId,
          sequence: prepared.sequence,
          retainedOperationIds: _checkpointRetainedOperationIds,
        );
        namespaceReplayed++;
      }

      await _persistCheckpoint(nextCheckpoint);

      totalReplayedOperations += namespaceReplayed;
      totalRecoveredWrites += namespaceRecoveredWrites;
      totalRecoveredDeletes += namespaceRecoveredDeletes;
      totalDuplicateSkips += namespaceDuplicateSkips;
      totalCorrupted += namespaceCorrupted;
      totalTruncated += truncatedEntries;

      namespaceReports.add(<String, dynamic>{
        'namespace': namespace,
        'replayed_operations': namespaceReplayed,
        'recovered_writes': namespaceRecoveredWrites,
        'recovered_deletes': namespaceRecoveredDeletes,
        'duplicate_operations_skipped': namespaceDuplicateSkips,
        'corrupted_journal_entries': namespaceCorrupted,
        'truncated_journal_entries': truncatedEntries,
        'issues': namespaceIssues,
      });
    }

    final finishedAt = DateTime.now().toUtc();
    final report = <String, dynamic>{
      'schema_version': _durabilitySchemaVersion,
      'started_at': startedAt.toIso8601String(),
      'finished_at': finishedAt.toIso8601String(),
      'abnormal_termination_detected': abnormalTerminationDetected,
      'totals': <String, dynamic>{
        'replayed_operations': totalReplayedOperations,
        'recovered_writes': totalRecoveredWrites,
        'recovered_deletes': totalRecoveredDeletes,
        'duplicate_operations_skipped': totalDuplicateSkips,
        'corrupted_journal_entries': totalCorrupted,
        'truncated_journal_entries': totalTruncated,
      },
      'namespaces': namespaceReports,
    };
    await _persistRecoveryReport(report);
    return report;
  }

  Future<bool> _recoverPreparedWrite(
    final _DurabilityJournalEntry prepared,
  ) async {
    final targetFile = File(path.join(_basePath, prepared.relativePath));
    if (!targetFile.parent.existsSync()) {
      await targetFile.parent.create(recursive: true);
    }

    if (prepared.tempRelativePath != null &&
        prepared.tempRelativePath!.isNotEmpty) {
      final tempFile = File(path.join(_basePath, prepared.tempRelativePath!));
      if (tempFile.existsSync()) {
        if (targetFile.existsSync()) {
          await targetFile.delete();
        }
        await tempFile.rename(targetFile.path);
        if (prepared.checksum.isEmpty) {
          return true;
        }
        return _fileChecksum(targetFile) == prepared.checksum;
      }
    }

    if (!targetFile.existsSync()) {
      return false;
    }
    if (prepared.checksum.isEmpty) {
      return true;
    }
    return _fileChecksum(targetFile) == prepared.checksum;
  }

  Future<bool> _recoverPreparedDelete(
    final _DurabilityJournalEntry prepared,
  ) async {
    final targetFile = File(path.join(_basePath, prepared.relativePath));
    if (targetFile.existsSync()) {
      await targetFile.delete();
    }
    return !targetFile.existsSync();
  }

  Future<_DurabilityCheckpoint> _loadCheckpoint(final String namespace) async {
    final cached = _checkpointCache[namespace];
    if (cached != null) {
      return cached;
    }

    final checkpointFile = File(_checkpointPath(namespace));
    if (!checkpointFile.existsSync()) {
      final empty = _DurabilityCheckpoint(namespace: namespace);
      _checkpointCache[namespace] = empty;
      return empty;
    }

    try {
      final decoded = jsonDecode(await checkpointFile.readAsString());
      if (decoded is! Map) {
        final empty = _DurabilityCheckpoint(namespace: namespace);
        _checkpointCache[namespace] = empty;
        return empty;
      }
      final checkpoint = _DurabilityCheckpoint.fromJson(
        namespace: namespace,
        json: Map<String, dynamic>.from(decoded),
      );
      _checkpointCache[namespace] = checkpoint;
      return checkpoint;
    } on FormatException {
      final empty = _DurabilityCheckpoint(namespace: namespace);
      _checkpointCache[namespace] = empty;
      return empty;
    }
  }

  Future<void> _persistCheckpoint(
    final _DurabilityCheckpoint checkpoint,
  ) async {
    _checkpointCache[checkpoint.namespace] = checkpoint;
    final checkpointFile = File(_checkpointPath(checkpoint.namespace));
    if (!checkpointFile.parent.existsSync()) {
      await checkpointFile.parent.create(recursive: true);
    }
    await checkpointFile.writeAsString(
      jsonEncode(checkpoint.toJson()),
      flush: true,
    );
  }

  Future<void> _appendJournalEntry(final _DurabilityJournalEntry entry) async {
    final journalFile = File(_journalPath(entry.namespace));
    if (!journalFile.parent.existsSync()) {
      await journalFile.parent.create(recursive: true);
    }
    await journalFile.writeAsString(
      '${jsonEncode(entry.toJson())}\n',
      mode: FileMode.append,
      flush: true,
    );
  }

  Future<void> _persistRecoveryReport(final Map<String, dynamic> report) async {
    final recoveryFile = File(_recoveryReportPath);
    if (!recoveryFile.parent.existsSync()) {
      await recoveryFile.parent.create(recursive: true);
    }
    await recoveryFile.writeAsString(jsonEncode(report), flush: true);
  }

  String _fileChecksum(final File file) =>
      normalizedSha256Hex(file.readAsStringSync());

  String _operationId({
    required final String namespace,
    required final int sequence,
    required final _DurabilityOperationType operationType,
  }) {
    final nowMicros = DateTime.now().toUtc().microsecondsSinceEpoch;
    return '${_sanitizeSegment(namespace)}:${operationType.name}:$sequence:$nowMicros';
  }

  String _tempRelativePath({
    required final String namespace,
    required final String operationId,
  }) {
    final safeNamespace = _sanitizeSegment(namespace);
    final safeOperationId = _sanitizeSegment(operationId);
    return path.join('.us', 'tmp', safeNamespace, '$safeOperationId.tmp');
  }

  String _namespaceForPath(final String relativePath) {
    final normalized = _normalizeRelativePath(relativePath);
    final separatorIndex = normalized.indexOf('/');
    if (separatorIndex <= 0) {
      return _rootNamespace;
    }
    return normalized.substring(0, separatorIndex);
  }

  String _normalizeRelativePath(final String rawPath) {
    final normalized = rawPath
        .trim()
        .replaceAll('\\', '/')
        .replaceAll(RegExp(r'/+'), '/')
        .replaceFirst(RegExp(r'^/'), '')
        .replaceFirst(RegExp(r'^\./'), '');
    if (normalized.isEmpty || normalized == '.') {
      throw ArgumentError.value(rawPath, 'filePath', 'Path must be non-empty.');
    }
    return normalized;
  }

  String _sanitizeSegment(final String value) => value
      .replaceAll(RegExp(r'[^A-Za-z0-9._-]'), '_')
      .replaceAll(RegExp(r'_+'), '_');

  String _journalPath(final String namespace) =>
      path.join(_journalRootPath, '${_sanitizeSegment(namespace)}.log');

  String _checkpointPath(final String namespace) =>
      path.join(_checkpointRootPath, '${_sanitizeSegment(namespace)}.json');

  String _namespaceFromJournalFile(final String journalFilePath) {
    final base = path.basenameWithoutExtension(journalFilePath);
    if (base.trim().isEmpty) {
      return _rootNamespace;
    }
    return base;
  }

  static Map<String, dynamic> _emptyRecoveryReport() => <String, dynamic>{
    'schema_version': _durabilitySchemaVersion,
    'started_at': DateTime.fromMillisecondsSinceEpoch(
      0,
    ).toUtc().toIso8601String(),
    'finished_at': DateTime.fromMillisecondsSinceEpoch(
      0,
    ).toUtc().toIso8601String(),
    'abnormal_termination_detected': false,
    'totals': <String, dynamic>{
      'replayed_operations': 0,
      'recovered_writes': 0,
      'recovered_deletes': 0,
      'duplicate_operations_skipped': 0,
      'corrupted_journal_entries': 0,
      'truncated_journal_entries': 0,
    },
    'namespaces': const <Map<String, dynamic>>[],
  };
}

enum _DurabilityOperationType { create, update, delete }

enum _DurabilityJournalStage { prepared, committed }

final class _DurabilityJournalEntry {
  const _DurabilityJournalEntry({
    required this.schemaVersion,
    required this.namespace,
    required this.operationId,
    required this.sequence,
    required this.operationType,
    required this.stage,
    required this.relativePath,
    required this.timestampUtc,
    this.tempRelativePath,
    this.checksum = '',
    this.recovered = false,
  });

  static _DurabilityJournalEntry? tryParse(final String jsonLine) {
    try {
      final dynamic decoded = jsonDecode(jsonLine);
      if (decoded is! Map) {
        return null;
      }
      final json = Map<String, dynamic>.from(decoded);

      final namespace = (json['namespace'] ?? '').toString().trim();
      final operationId = (json['operation_id'] ?? '').toString().trim();
      final relativePath = (json['relative_path'] ?? '').toString().trim();
      final operationTypeName = (json['operation_type'] ?? '')
          .toString()
          .trim();
      final stageName = (json['stage'] ?? '').toString().trim();
      final sequence = json['sequence'] is int ? json['sequence'] as int : -1;

      if (namespace.isEmpty ||
          operationId.isEmpty ||
          relativePath.isEmpty ||
          sequence < 0) {
        return null;
      }

      final operationType = _DurabilityOperationType.values.firstWhere(
        (final value) => value.name == operationTypeName,
        orElse: () => _DurabilityOperationType.update,
      );
      final stage = _DurabilityJournalStage.values.firstWhere(
        (final value) => value.name == stageName,
        orElse: () => _DurabilityJournalStage.prepared,
      );

      final timestampUtc =
          DateTime.tryParse(
            (json['timestamp_utc'] ?? '').toString(),
          )?.toUtc() ??
          DateTime.fromMillisecondsSinceEpoch(0).toUtc();

      return _DurabilityJournalEntry(
        schemaVersion: json['schema_version'] is int
            ? json['schema_version'] as int
            : 1,
        namespace: namespace,
        operationId: operationId,
        sequence: sequence,
        operationType: operationType,
        stage: stage,
        relativePath: relativePath,
        timestampUtc: timestampUtc,
        tempRelativePath: json['temp_relative_path']?.toString(),
        checksum: (json['checksum'] ?? '').toString(),
        recovered: json['recovered'] == true,
      );
    } on FormatException {
      return null;
    }
  }

  final int schemaVersion;
  final String namespace;
  final String operationId;
  final int sequence;
  final _DurabilityOperationType operationType;
  final _DurabilityJournalStage stage;
  final String relativePath;
  final DateTime timestampUtc;
  final String? tempRelativePath;
  final String checksum;
  final bool recovered;

  _DurabilityJournalEntry copyWith({
    final _DurabilityJournalStage? stage,
    final bool? recovered,
  }) => _DurabilityJournalEntry(
    schemaVersion: schemaVersion,
    namespace: namespace,
    operationId: operationId,
    sequence: sequence,
    operationType: operationType,
    stage: stage ?? this.stage,
    relativePath: relativePath,
    timestampUtc: DateTime.now().toUtc(),
    tempRelativePath: tempRelativePath,
    checksum: checksum,
    recovered: recovered ?? this.recovered,
  );

  Map<String, dynamic> toJson() => <String, dynamic>{
    'schema_version': schemaVersion,
    'namespace': namespace,
    'operation_id': operationId,
    'sequence': sequence,
    'operation_type': operationType.name,
    'stage': stage.name,
    'relative_path': relativePath,
    'timestamp_utc': timestampUtc.toIso8601String(),
    if (tempRelativePath != null) 'temp_relative_path': tempRelativePath,
    'checksum': checksum,
    'recovered': recovered,
  };
}

final class _DurabilityReplayOperation {
  _DurabilityReplayOperation({required this.operationId});

  final String operationId;
  _DurabilityJournalEntry? preparedEntry;
  var committed = false;
  var sequence = 0;

  void track(final _DurabilityJournalEntry entry) {
    if (entry.sequence > sequence) {
      sequence = entry.sequence;
    }
    if (entry.stage == _DurabilityJournalStage.prepared) {
      preparedEntry = entry;
    } else if (entry.stage == _DurabilityJournalStage.committed) {
      committed = true;
    }
  }
}

final class _DurabilityCheckpoint {
  const _DurabilityCheckpoint({
    required this.namespace,
    this.lastSequence = 0,
    this.appliedOperationIds = const <String>{},
  });

  factory _DurabilityCheckpoint.fromJson({
    required final String namespace,
    required final Map<String, dynamic> json,
  }) {
    final rawApplied = json['applied_operation_ids'];
    final applied = <String>{};
    if (rawApplied is List) {
      for (final value in rawApplied) {
        final id = value?.toString() ?? '';
        if (id.isNotEmpty) {
          applied.add(id);
        }
      }
    }

    return _DurabilityCheckpoint(
      namespace: namespace,
      lastSequence: json['last_sequence'] is int
          ? json['last_sequence'] as int
          : 0,
      appliedOperationIds: applied,
    );
  }

  final String namespace;
  final int lastSequence;
  final Set<String> appliedOperationIds;

  _DurabilityCheckpoint markApplied({
    required final String operationId,
    required final int sequence,
    required final int retainedOperationIds,
  }) {
    final nextApplied = appliedOperationIds.toList(growable: true)
      ..add(operationId);
    if (nextApplied.length > retainedOperationIds) {
      nextApplied.removeRange(0, nextApplied.length - retainedOperationIds);
    }
    return _DurabilityCheckpoint(
      namespace: namespace,
      lastSequence: sequence > lastSequence ? sequence : lastSequence,
      appliedOperationIds: nextApplied.toSet(),
    );
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
    'schema_version': 1,
    'namespace': namespace,
    'last_sequence': lastSequence,
    'applied_operation_ids': appliedOperationIds.toList(growable: false),
    'updated_at': DateTime.now().toUtc().toIso8601String(),
  };
}
