// ignore_for_file: lines_longer_than_80_chars

/// J1/J2 — the intent-closure AFM runner, as a LIBRARY so its pieces are
/// measurable and benchmarkable (K protocol). The bin driver owns only the
/// process plumbing (native client load, meter, stdout).
///
/// `Agent = G ∘ F`: prompts and tool surfaces are data; the oracle is a
/// deterministic dart subprocess; the verifier loop is mechanical.
library;

import 'dart:io';

import 'package:xsoulspace_agentic_harness/xsoulspace_agentic_harness.dart';
import 'package:xsoulspace_agentic_harness/src/tooling/act_with_project.dart'
    show actWithProjectTool;
import 'package:xsoulspace_agentic_harness/src/tools/fs_tools.dart'
    show FsToolsRoot, runTool;

/// J1.5.5 — the shared decision meter: counts decisions (generate calls) and
/// honest projection tokens (Situation.tokensUsed). Move counts come from
/// the world's durable tool beats AFTER the run — internal tool rounds never
/// surface on the final response, so they must be read from thread history.
/// Extracted here so `bin/intent_closure_afm.dart` and
/// `bin/coding_agent.dart` share ONE implementation (K columns must be
/// measured the same way to be comparable).
class DecisionMeter implements GenerationHandler {
  DecisionMeter(this.inner);
  final GenerationHandler inner;
  int decisions = 0;
  int projectionTokens = 0;

  @override
  Future<ActorGenerateResponse> generate(
    World world,
    ActorGenerateRequest request,
  ) async {
    final situation = world.getEntity(request.actorEntity).$1.get<Situation>();
    if (situation != null) projectionTokens += situation.tokensUsed;
    final response = await inner.generate(world, request);
    decisions++;
    return response;
  }
}

/// J1.5.5 — Ctrl-C during an on-device run still leaves a post-mortem.
void wireSigintDump(FlightRecorder recorder) {
  ProcessSignal.sigint.watch().listen((_) {
    stderr
      ..writeln('SIGINT — flight recorder dump (J1.5.3):')
      ..writeln(recorder.dump());
    exit(130);
  });
}

/// J1.2 — measured, budgeted system prompt (~180 tokens). Teaching the flow
/// lives HERE and in tool descriptions — nowhere else. B1: `define` is ONE
/// self-executing action (REQUIRES specs — an intent without specs has no
/// executor and can never be called).
const afmSystemPrompt =
    'You build a bookmark manager by picking tiny moves. You never write '
    'code. Tools: intent_define, act_with_project, intent_call.\n'
    'Flow: 1) intent_define action define WITH specs — ONE move defines '
    'the intent AND wires its whole op chain. Define save_url (param '
    '"url:string", returns bool), then list_saved (returns int). Op '
    'vocabulary: load_arg, load_state, push_state, literal, list_len, '
    'starts_with, eq, not, jump_if_false, return. Spec rows: label + '
    'props a/b; jump targets use "#row" (e.g. "#5"); each row continues '
    'to the next row unless "next" says otherwise. '
    '2) act_with_project action materialize. 3) intent_call save_url then '
    'intent_call list_saved to verify.';

const afmTaskPrompt =
    'Build a bookmark manager: save_url saves a URL only if it starts with '
    'http; list_saved counts saved bookmarks. Build, materialize, verify.';

/// The intent-graded oracle: same shape as the suite's `intents` checker
/// (checkers.dart). Deterministic — real Dart subprocess, real program.dart.
const intentRunnerSource = r'''
// GENERATED by intent_closure_afm (Stage I3 oracle).
// Replays scripted intent calls against the materialized program
// (program.dart: initialState() + runIntent(name, state, args)) and exits 0
// iff every expectation holds.
import 'dart:convert';
import 'dart:io';
import 'program.dart' as program;

void main() {
  final spec = jsonDecode(File('intent_calls.json').readAsStringSync()) as Map;
  final calls = (spec['calls'] as List).cast<Map>();
  var state = program.initialState();
  var ok = true;
  final log = <String>[];
  for (final call in calls) {
    final name = call['intent'] as String;
    final args =
        ((call['args'] ?? const {}) as Map).cast<String, dynamic>();
    final expect =
        ((call['expect'] ?? const {}) as Map).cast<String, dynamic>();
    Map<String, dynamic> result;
    try {
      result = program.runIntent(name, state, args);
      state = (result['_state'] ?? state) as Map<String, dynamic>;
      result = (result['_result'] ?? result) as Map<String, dynamic>;
    } catch (e) {
      result = {'error': e.toString()};
    }
    final callOk = !result.containsKey('error') &&
        expect.entries.every((e) => result[e.key] == e.value);
    ok = ok && callOk;
    log.add(name + ' -> ' + result.toString());
  }
  stdout.writeln(ok
      ? 'intents: all ' + calls.length.toString() + ' calls verified'
      : 'intents failed: ' + log.join('; '));
  exit(ok ? 0 : 1);
}
''';

const oracleCallsJson =
    '{"calls": [\n'
    '  {"intent": "save_url", "args": {"url": "https://example.dev"}, "expect": {"saved": true}},\n'
    '  {"intent": "save_url", "args": {"url": "https://second.dev"}},\n'
    '  {"intent": "list_saved", "expect": {"value": 2}},\n'
    '  {"intent": "save_url", "args": {"url": "not-a-url"}, "expect": {"saved": false}}\n'
    ']}';

/// Registers the intent-closure tool surface AND returns the defs so the
/// context overhead can be measured (J1.2) — one truth, two uses.
List<ToolDef> registerIntentClosureTools(World world, Directory jail) {
  final registry = ToolRegistry();
  final tools = <ToolDef>[
    actWithProjectTool(
      world: world,
      materialize: () async {
        // Host program: meaning tree (op chains) -> real program.dart.
        final src = materializeMeaningProgram(world);
        File('${jail.path}/program.dart').writeAsStringSync(src);
        return {
          'path': 'program.dart',
          'materialized': true,
          'intents': [for (final i in listIntents(world)) i['name']],
          // Host-side chain validation: broken impl chains are caught NOW
          // (op ids included) instead of one oracle round later.
          'problems': validateMeaningProgram(world),
        };
      },
    ),
    intentDefineTool(world),
    intentCallTool(world),
    runTool(FsToolsRoot(jail.path)),
  ];
  for (final t in tools) {
    registry.register(t);
  }
  world.getResource<ToolRegistryResource>().register('default', registry);
  return tools;
}

/// Runs the intent-graded oracle against [jail]: writes the runner + calls
/// spec, executes `dart run intent_runner.dart`, returns the process result.
/// A missing program.dart is a structured failure (exit -1), not a throw.
Future<ProcessResult> runIntentOracle(Directory jail) async {
  File('${jail.path}/intent_calls.json').writeAsStringSync(oracleCallsJson);
  File('${jail.path}/intent_runner.dart').writeAsStringSync(intentRunnerSource);
  final program = File('${jail.path}/program.dart');
  if (!program.existsSync()) {
    return ProcessResult(0, -1, '', 'program.dart never materialized');
  }
  return Process.run(
    'dart', ['run', 'intent_runner.dart'],
    workingDirectory: jail.path,
  );
}
