name: xsoulspace_inference_flutter_example
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  xsoulspace_inference_core:
    path: ../../xsoulspace_inference_core
  xsoulspace_inference_flutter:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
